import type { Reference } from '@/types/history';

const accessedAt = '2026-10-02';
export const expansionReferences: Reference[] = [
  {
    id: 'hebb-1949',
    type: 'book',
    title: 'The Organization of Behavior: A Neuropsychological Theory',
    authors: ['Donald O. Hebb'],
    year: 1949,
    url: 'https://pure.mpg.de/pubman/item/item_2346268_3/component/file_2346267/Hebb_1949_The_Organization_of_Behavior.pdf',
    accessedAt,
  },
  {
    id: 'hebb-mcgill',
    yearKind: 'access',
    type: 'archive',
    title: 'Donald HEBB, PhD',
    authors: ['McGill University'],
    year: 2026,
    url: 'https://www.mcgill.ca/neuro/about/donald-hebb-phd',
    accessedAt,
    notes: 'Undated institutional biography; year is access-year.',
  },
  {
    id: 'turing-1936',
    type: 'archive',
    title: 'Computable numbers',
    authors: ['Alan M. Turing', 'King’s College Archive Centre'],
    year: 1936,
    url: 'https://turingarchive.kings.cam.ac.uk/computable-numbers',
    accessedAt,
    notes: 'Archive of the 1936 paper; journal volume is also commonly dated 1937.',
  },
  {
    id: 'turing-1950',
    type: 'archive',
    title: 'Computing machinery and intelligence',
    authors: ['Alan M. Turing'],
    year: 1950,
    url: 'https://turingarchive.kings.cam.ac.uk/computing-machinery-and-intelligence',
    doi: '10.1093/mind/LIX.236.433',
    accessedAt,
  },
  {
    id: 'edvac-1945',
    type: 'archive',
    title: 'First Draft of a Report on the EDVAC',
    authors: ['John von Neumann'],
    year: 1945,
    url: 'https://people.csail.mit.edu/brooks/idocs/VonNeumann_EDVAC.pdf',
    accessedAt,
    notes:
      'Corrected transcription of the report dated June 30, 1945. Section 4 explicitly discusses a neural analogy.',
  },
  {
    id: 'shannon-1948',
    type: 'paper',
    title: 'A Mathematical Theory of Communication',
    authors: ['Claude E. Shannon'],
    year: 1948,
    url: 'https://www.princeton.edu/~wbialek/rome/refs/shannon_48.pdf',
    doi: '10.1002/j.1538-7305.1948.tb01338.x',
    accessedAt,
  },
  {
    id: 'wiener-1948',
    type: 'book',
    title: 'Cybernetics or Control and Communication in the Animal and the Machine',
    authors: ['Norbert Wiener'],
    year: 1948,
    url: 'https://mitpress.mit.edu/9780262355919/cybernetics-or-control-and-communication-in-the-animal-and-the-machine/',
    accessedAt,
    notes:
      'Publisher page for a later edition explicitly dates first publication to 1948 and confirms Wiener’s MIT affiliation.',
  },
  {
    id: 'dartmouth-proposal',
    type: 'archive',
    title: 'A Proposal for the Dartmouth Summer Research Project on Artificial Intelligence',
    authors: ['John McCarthy', 'Marvin L. Minsky', 'Nathaniel Rochester', 'Claude E. Shannon'],
    year: 1955,
    url: 'https://www-formal.stanford.edu/jmc/history/dartmouth/dartmouth.html',
    accessedAt,
  },
  {
    id: 'dartmouth-recollection',
    type: 'archive',
    title: 'The Dartmouth Workshop: as planned and as it happened',
    authors: ['John McCarthy'],
    year: 2006,
    url: 'https://www-formal.stanford.edu/jmc/slides/dartmouth/dartmouth/node1.html',
    accessedAt,
    notes:
      'Participant recollection; distinguish retrospective interpretation from the contemporary proposal.',
  },
  {
    id: 'logic-theory-1956',
    type: 'paper',
    title: 'The Logic Theory Machine: A Complex Information Processing System',
    authors: ['Allen Newell', 'Herbert A. Simon'],
    year: 1956,
    url: 'https://www.rand.org/pubs/papers/P868.html',
    doi: '10.7249/P868',
    accessedAt,
  },
  {
    id: 'rand-history',
    type: 'archive',
    title: 'RAND and the Information Evolution: A History in Essays and Vignettes',
    authors: ['Willis H. Ware'],
    year: 2008,
    url: 'https://www.rand.org/content/dam/rand/pubs/corporate_pubs/2008/RAND_CP537.pdf',
    accessedAt,
    notes: 'Institutional history documents the Newell, Shaw and Simon collaboration.',
  },
  {
    id: 'minsky-papert-1969',
    type: 'book',
    title: 'Perceptrons: An Introduction to Computational Geometry',
    authors: ['Marvin Minsky', 'Seymour A. Papert'],
    year: 1969,
    url: 'https://mitpress.mit.edu/9780262130431/perceptrons/',
    accessedAt,
  },
  {
    id: 'agar-2020',
    type: 'paper',
    title: 'What is science for? The Lighthill report on artificial intelligence reinterpreted',
    authors: ['Jon Agar'],
    year: 2020,
    url: 'https://www.cambridge.org/core/journals/british-journal-for-the-history-of-science/article/abs/what-is-science-for-the-lighthill-report-on-artificial-intelligence-reinterpreted/61B13B32988D6A8C58CF8AADD4777789',
    accessedAt,
  },
  {
    id: 'haigh-2023',
    type: 'paper',
    title: 'There Was No First AI Winter',
    authors: ['Thomas Haigh'],
    year: 2023,
    url: 'https://zoo.cs.yale.edu/classes/cs200/lectures/AIACMDec2023.pdf',
    doi: '10.1145/3625833',
    accessedAt,
    notes:
      'Historical interpretation contesting the familiar first-winter narrative, not a universal consensus.',
  },
  {
    id: 'hopfield-1982',
    type: 'paper',
    title: 'Neural networks and physical systems with emergent collective computational abilities',
    authors: ['John J. Hopfield'],
    year: 1982,
    url: 'https://authors.library.caltech.edu/records/w41x7-8bn13',
    doi: '10.1073/pnas.79.8.2554',
    accessedAt,
  },
  {
    id: 'nobel-physics-2024',
    yearKind: 'award',
    type: 'nobel',
    title: 'The Nobel Prize in Physics 2024',
    authors: ['Royal Swedish Academy of Sciences'],
    year: 2024,
    url: 'https://www.nobelprize.org/prizes/physics/2024/press-release/',
    accessedAt,
    notes:
      'Joint award to John Hopfield and Geoffrey Hinton. Indexed official record and official press-release PDF consulted.',
  },
  {
    id: 'mnist-creators',
    type: 'website',
    title: 'The MNIST Database of Handwritten Digits',
    authors: ['Yann LeCun', 'Corinna Cortes', 'Christopher J. C. Burges'],
    year: 1998,
    url: 'https://yann.lecun.org/exdb/mnist/index.html',
    accessedAt,
    notes:
      '1998 is the atlas milestone tied to LeCun et al. 1998, not a claimed publication date of this changing webpage. Current affiliations on the page are not historical affiliations.',
  },
  {
    id: 'bellman-1957',
    type: 'book',
    title: 'Dynamic Programming',
    authors: ['Richard Bellman'],
    year: 1957,
    url: 'https://press.princeton.edu/books/paperback/9780691146683/dynamic-programming',
    accessedAt,
    notes:
      'Original publication 1957; link is to a later reprint. Bibliographic date confirmed through institutional library metadata.',
  },
  {
    id: 'bellman-communication',
    type: 'paper',
    title: 'Dynamic Programming and Statistical Communication Theory',
    authors: ['Richard Bellman'],
    year: 1957,
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC528532/',
    doi: '10.1073/pnas.43.8.749',
    accessedAt,
  },
  {
    id: 'sutton-1988',
    type: 'paper',
    title: 'Learning to Predict by the Methods of Temporal Differences',
    authors: ['Richard S. Sutton'],
    year: 1988,
    url: 'https://jmvidal.cse.sc.edu/library/sutton88a.pdf',
    doi: '10.1007/BF00115009',
    accessedAt,
  },
  {
    id: 'watkins-dayan-1992',
    type: 'paper',
    title: 'Q-learning',
    authors: ['Christopher J. C. H. Watkins', 'Peter Dayan'],
    year: 1992,
    url: 'https://www.gatsby.ucl.ac.uk/~dayan/papers/cjch.pdf',
    doi: '10.1007/BF00992698',
    accessedAt,
    notes:
      'Builds on Watkins’s 1989 Cambridge dissertation. The paper’s affiliations are London and Edinburgh.',
  },
  {
    id: 'schultz-dayan-montague-1997',
    type: 'paper',
    title: 'A Neural Substrate of Prediction and Reward',
    authors: ['Wolfram Schultz', 'Peter Dayan', 'P. Read Montague'],
    year: 1997,
    url: 'https://web.math.princeton.edu/~sswang/fundamental-readings-for-Wang-lab-members/schultz_montague97_science.pdf',
    doi: '10.1126/science.275.5306.1593',
    accessedAt,
  },
  {
    id: 'dqn-2013',
    type: 'paper',
    title: 'Playing Atari with Deep Reinforcement Learning',
    authors: [
      'Volodymyr Mnih',
      'Koray Kavukcuoglu',
      'David Silver',
      'Alex Graves',
      'Ioannis Antonoglou',
      'Daan Wierstra',
      'Martin Riedmiller',
    ],
    year: 2013,
    url: 'https://arxiv.org/abs/1312.5602',
    accessedAt,
  },
  {
    id: 'dqn-2015',
    type: 'paper',
    title: 'Human-level control through deep reinforcement learning',
    authors: ['Volodymyr Mnih', 'Koray Kavukcuoglu', 'David Silver', 'and colleagues'],
    year: 2015,
    url: 'https://www.nature.com/articles/nature14236',
    doi: '10.1038/nature14236',
    accessedAt,
    notes: 'Abbreviated author list; complete authorship is available at the source.',
  },
  {
    id: 'alphago-2016',
    type: 'paper',
    title: 'Mastering the game of Go with deep neural networks and tree search',
    authors: ['David Silver', 'Aja Huang', 'Chris J. Maddison', 'and colleagues'],
    year: 2016,
    url: 'https://www.nature.com/articles/nature16961',
    doi: '10.1038/nature16961',
    accessedAt,
    notes: 'Abbreviated author list; complete authorship at source.',
  },
  {
    id: 'alphago-zero-2017',
    type: 'paper',
    title: 'Mastering the game of Go without human knowledge',
    authors: ['David Silver', 'Julian Schrittwieser', 'Karen Simonyan', 'and colleagues'],
    year: 2017,
    url: 'https://www.nature.com/articles/nature24270',
    doi: '10.1038/nature24270',
    accessedAt,
    notes: 'Abbreviated author list; complete authorship at source.',
  },
  {
    id: 'rao-ballard-1999',
    type: 'paper',
    title:
      'Predictive coding in the visual cortex: a functional interpretation of some extra-classical receptive-field effects',
    authors: ['Rajesh P. N. Rao', 'Dana H. Ballard'],
    year: 1999,
    url: 'https://www.nature.com/articles/nn0199_79',
    doi: '10.1038/4580',
    accessedAt,
  },
  {
    id: 'transformer-2017',
    type: 'paper',
    title: 'Attention Is All You Need',
    authors: [
      'Ashish Vaswani',
      'Noam Shazeer',
      'Niki Parmar',
      'Jakob Uszkoreit',
      'Llion Jones',
      'Aidan N. Gomez',
      'Łukasz Kaiser',
      'Illia Polosukhin',
    ],
    year: 2017,
    url: 'https://arxiv.org/abs/1706.03762',
    accessedAt,
  },
  {
    id: 'bert-2018',
    type: 'paper',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
    authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
    year: 2018,
    url: 'https://arxiv.org/abs/1810.04805',
    accessedAt,
    notes: '2018 preprint; final NAACL publication in 2019.',
  },
  {
    id: 'alphafold-2021',
    type: 'paper',
    title: 'Highly accurate protein structure prediction with AlphaFold',
    authors: ['John Jumper', 'Richard Evans', 'Alexander Pritzel', 'and colleagues'],
    year: 2021,
    url: 'https://www.nature.com/articles/s41586-021-03819-2',
    doi: '10.1038/s41586-021-03819-2',
    accessedAt,
    notes:
      'Abbreviated author list; complete authorship at source. Describes AlphaFold2 following CASP14 in 2020.',
  },
  {
    id: 'nobel-chemistry-2024',
    yearKind: 'award',
    type: 'nobel',
    title:
      'The Nobel Prize in Chemistry 2024: They cracked the code for proteins’ amazing structures',
    authors: ['Royal Swedish Academy of Sciences'],
    year: 2024,
    url: 'https://www.nobelprize.org/uploads/2024/11/popular-chemistryprize2024.pdf',
    accessedAt,
    notes:
      'Baker received one half for computational protein design; Hassabis and Jumper jointly received the other half for protein structure prediction.',
  },
  {
    id: 'foundation-2021',
    type: 'paper',
    title: 'On the Opportunities and Risks of Foundation Models',
    authors: ['Rishi Bommasani', 'Drew A. Hudson', 'Ehsan Adeli', 'and colleagues'],
    year: 2021,
    url: 'https://arxiv.org/abs/2108.07258',
    accessedAt,
    notes:
      'Abbreviated author list; complete authorship at source. A Stanford CRFM report introducing this terminology.',
  },
  {
    id: 'neuroai-2023',
    type: 'paper',
    title: 'Catalyzing next-generation Artificial Intelligence through NeuroAI',
    authors: ['Anthony Zador', 'Sean Escola', 'Blake Richards', 'Bence Ölveczky', 'and colleagues'],
    year: 2023,
    url: 'https://www.nature.com/articles/s41467-023-37180-x',
    doi: '10.1038/s41467-023-37180-x',
    accessedAt,
    notes:
      'Perspective and research agenda, not a demonstrated universal theory. Abbreviated author list; complete list at source.',
  },
  {
    id: 'hodgkin-huxley-1952',
    type: 'paper',
    title:
      'A quantitative description of membrane current and its application to conduction and excitation in nerve',
    authors: ['Alan L. Hodgkin', 'Andrew F. Huxley'],
    year: 1952,
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1392413/',
    doi: '10.1113/jphysiol.1952.sp004764',
    accessedAt,
  },
];
