import type { Reference } from '@/types/history';

// Bibliographic titles retain their original publication language.
export const initialReferences: Reference[] = [
  {
    id: 'golgi-pavia',
    type: 'archive',
    title: 'Camillo Golgi',
    authors: ['Museo per la Storia dell’Università di Pavia'],
    year: 2026,
    yearKind: 'access',
    url: 'https://museoperlastoria.unipv.it/en/camillo-golgi-2/',
    accessedAt: '2026-10-02',
    notes:
      'Institutional history; date is access-year because the page is undated. Documents the 1872–1873 work in Abbiategrasso.',
  },
  {
    id: 'golgi-black-reaction',
    type: 'nobel',
    title: 'Black Reaction: La reazione nera',
    authors: ['Nobel Prize Outreach'],
    year: 1906,
    url: 'https://www.nobelprize.org/prizes/medicine/1906/7606-the-black-reaction-la-reazione-nera/',
    accessedAt: '2026-10-02',
    notes:
      'Prize year, not webpage publication year. Search-index content was accessible; direct retrieval returned HTTP 403.',
  },
  {
    id: 'nobel-1906',
    type: 'nobel',
    title: 'The Nobel Prize in Physiology or Medicine 1906',
    authors: ['Nobel Prize Outreach'],
    year: 1906,
    url: 'https://www.nobelprize.org/prizes/medicine/1906/summary/',
    accessedAt: '2026-10-02',
    notes: 'Award record confirmed through indexed Nobel page. Direct retrieval returned HTTP 403.',
  },
  {
    id: 'cajal-lecture',
    type: 'nobel',
    title: 'The structure and connexions of neurons',
    authors: ['Santiago Ramón y Cajal'],
    year: 1906,
    url: 'https://www.nobelprize.org/uploads/2018/06/cajal-lecture.pdf',
    accessedAt: '2026-10-02',
    notes: 'Nobel lecture. Indexed text consulted; direct PDF retrieval returned HTTP 403.',
  },
  {
    id: 'cajal-barcelona',
    type: 'archive',
    title: 'History: Faculty of Medicine and Health Sciences',
    authors: ['University of Barcelona'],
    year: 2026,
    yearKind: 'access',
    url: 'https://www.ub.edu/portal/web/medicine-health-sciences/history',
    accessedAt: '2026-10-02',
    notes:
      'Undated institutional history; year indicates access-year. Supports Barcelona appointment, 1887–1892, and 1888 milestone.',
  },
  {
    id: 'neuron-history',
    type: 'archive',
    title: 'Beyond the Temples of Science: Bohemian Neuroscience in Fin-de-siècle Berlin',
    authors: ['Sven Dierig', 'Dennis Meyhoff Brink'],
    year: 2006,
    url: 'https://vlp.mpiwg-berlin.mpg.de/essays/data/art44',
    accessedAt: '2026-10-02',
    notes: 'Max Planck Virtual Laboratory essay; section 8 discusses Waldeyer’s 1891 terminology.',
  },
  {
    id: 'nobel-cells',
    type: 'nobel',
    title: 'Exploring life’s smallest details',
    authors: ['Nobel Prize Outreach'],
    year: 2026,
    yearKind: 'access',
    url: 'https://www.nobelprize.org/stories/cells-nerves-genes/',
    accessedAt: '2026-10-02',
  },
  {
    id: 'mcculloch-pitts-1943',
    type: 'paper',
    title: 'A logical calculus of the ideas immanent in nervous activity',
    authors: ['Warren S. McCulloch', 'Walter Pitts'],
    year: 1943,
    url: 'https://link.springer.com/article/10.1007/BF02478259',
    doi: '10.1007/BF02478259',
    accessedAt: '2026-10-02',
  },
  {
    id: 'rosenblatt-1958',
    type: 'paper',
    title:
      'The perceptron: A probabilistic model for information storage and organization in the brain',
    authors: ['Frank Rosenblatt'],
    year: 1958,
    url: 'https://doi.org/10.1037/h0042519',
    doi: '10.1037/h0042519',
    accessedAt: '2026-10-02',
    notes:
      'Publication metadata verified; original title and abstract indexed. Publisher direct retrieval was unavailable.',
  },
  {
    id: 'rosenblatt-cornell',
    type: 'archive',
    title: 'Professor’s perceptron paved the way for AI, 60 years too soon',
    authors: ['Cornell University'],
    year: 2019,
    url: 'https://as.cornell.edu/news/professors-perceptron-paved-way-ai-60-years-too-soon',
    accessedAt: '2026-10-02',
  },
  {
    id: 'perceptron-course',
    type: 'website',
    title: 'The Perceptron Algorithm',
    authors: ['University of Utah, School of Computing'],
    year: 2018,
    url: 'https://users.cs.utah.edu/~zhe/pdf/lec-10-perceptron-upload.pdf',
    accessedAt: '2026-10-02',
    notes:
      'Institutional teaching source for the explicitly modernized demonstration and separability condition.',
  },
  {
    id: 'hubel-wiesel-1962',
    type: 'paper',
    title:
      'Receptive fields, binocular interaction and functional architecture in the cat’s visual cortex',
    authors: ['David H. Hubel', 'Torsten N. Wiesel'],
    year: 1962,
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1359523/',
    doi: '10.1113/jphysiol.1962.sp006837',
    accessedAt: '2026-10-02',
  },
  {
    id: 'hubel-harvard',
    type: 'archive',
    title: 'Nobel laureate Hubel dies at 87',
    authors: ['Harvard Medical School'],
    year: 2013,
    url: 'https://news.harvard.edu/gazette/story/2013/09/nobel-laureate-hubel-dies-at-87/',
    accessedAt: '2026-10-02',
  },
  {
    id: 'nobel-1981',
    type: 'nobel',
    title: 'The Nobel Prize in Physiology or Medicine 1981',
    authors: ['Nobel Prize Outreach'],
    year: 1981,
    url: 'https://www.nobelprize.org/prizes/medicine/1981/summary/',
    accessedAt: '2026-10-02',
    notes:
      'Hubel and Wiesel shared one half; Roger Sperry received the other half. Award record verified through indexed Nobel page.',
  },
  {
    id: 'fukushima-1980',
    type: 'paper',
    title:
      'Neocognitron: A self-organizing neural network model for a mechanism of pattern recognition unaffected by shift in position',
    authors: ['Kunihiko Fukushima'],
    year: 1980,
    url: 'https://link.springer.com/article/10.1007/BF00344251',
    doi: '10.1007/BF00344251',
    accessedAt: '2026-10-02',
  },
  {
    id: 'rumelhart-1986',
    type: 'paper',
    title: 'Learning representations by back-propagating errors',
    authors: ['David E. Rumelhart', 'Geoffrey E. Hinton', 'Ronald J. Williams'],
    year: 1986,
    url: 'https://www.cs.toronto.edu/~hinton/absps/naturebp.pdf',
    doi: '10.1038/323533a0',
    accessedAt: '2026-10-02',
  },
  {
    id: 'autodiff-history',
    type: 'review',
    title: 'Automatic differentiation in machine learning: a survey',
    authors: [
      'Atılım Güneş Baydin',
      'Barak A. Pearlmutter',
      'Alexey Andreyevich Radul',
      'Jeffrey Mark Siskind',
    ],
    year: 2018,
    url: 'https://jmlr.csail.mit.edu/papers/volume18/17-468/17-468.pdf',
    accessedAt: '2026-10-02',
    notes:
      'Documents reverse-mode differentiation before the 1986 neural-network paper, including Linnainmaa’s 1970 work.',
  },
  {
    id: 'lecun-1998',
    type: 'paper',
    title: 'Gradient-Based Learning Applied to Document Recognition',
    authors: ['Yann LeCun', 'Léon Bottou', 'Yoshua Bengio', 'Patrick Haffner'],
    year: 1998,
    url: 'https://bottou.org/papers/lecun-98h',
    doi: '10.1109/5.726791',
    accessedAt: '2026-10-02',
  },
  {
    id: 'imagenet-2009',
    type: 'paper',
    title: 'ImageNet: A Large-Scale Hierarchical Image Database',
    authors: ['Jia Deng', 'Wei Dong', 'Richard Socher', 'Li-Jia Li', 'Kai Li', 'Li Fei-Fei'],
    year: 2009,
    url: 'https://www.image-net.org/static_files/papers/imagenet_cvpr09.pdf',
    doi: '10.1109/CVPR.2009.5206848',
    accessedAt: '2026-10-02',
  },
  {
    id: 'ilsvrc-2015',
    type: 'paper',
    title: 'ImageNet Large Scale Visual Recognition Challenge',
    authors: [
      'Olga Russakovsky',
      'Jia Deng',
      'Hao Su',
      'Jonathan Krause',
      'Sanjeev Satheesh',
      'Sean Ma',
      'Zhiheng Huang',
      'Andrej Karpathy',
      'Aditya Khosla',
      'Michael Bernstein',
      'Alexander C. Berg',
      'Li Fei-Fei',
    ],
    year: 2015,
    url: 'https://arxiv.org/abs/1409.0575',
    doi: '10.1007/s11263-015-0816-y',
    accessedAt: '2026-10-02',
  },
  {
    id: 'alexnet-2012',
    type: 'paper',
    title: 'ImageNet Classification with Deep Convolutional Neural Networks',
    authors: ['Alex Krizhevsky', 'Ilya Sutskever', 'Geoffrey E. Hinton'],
    year: 2012,
    url: 'https://papers.nips.cc/paper_files/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html',
    accessedAt: '2026-10-02',
  },
];
