import type { HistoricalEntity, LocalizedText, LocationReference } from '@/types/history';

const t = (en: string, de: string, es: string): LocalizedText => ({ en, de, es });
const place = (
  name: string,
  institution: string,
  lat: number,
  lon: number,
  year: number,
): LocationReference => ({ name, institution, lat, lon, year });

export const expansionEntities: HistoricalEntity[] = [
  {
    id: 'hebb',
    demo: 'hebbian',
    slug: 'hebb',
    type: 'concept',
    title: t(
      'Hebb: learning changes connections',
      'Hebb: Lernen verändert Verbindungen',
      'Hebb: aprender cambia las conexiones',
    ),
    shortDescription: t(
      'Donald Hebb connected learning with changes between active nerve cells. His cell assemblies offered a way to think about how experience could leave a physical trace.',
      'Donald Hebb verband Lernen mit Veränderungen zwischen aktiven Nervenzellen. Seine Zellverbände boten eine Erklärung dafür, wie Erfahrung eine physische Spur hinterlassen könnte.',
      'Donald Hebb relacionó el aprendizaje con cambios entre células nerviosas activas. Sus asambleas celulares ofrecían una explicación de cómo la experiencia podía dejar una huella física.',
    ),
    description: t(
      'In The Organization of Behavior, Hebb proposed that repeated participation in another cell’s firing could strengthen a connection. Groups of cooperating cells could then support perception and memory. Published in 1949 while he worked at McGill, the book joined psychological questions to biological mechanisms. It offered a hypothesis about learning, not a complete description of synaptic plasticity. Later mathematical learning rules simplified this proposal in different ways.',
      'In The Organization of Behavior schlug Hebb vor, dass die wiederholte Beteiligung an der Aktivierung einer anderen Zelle eine Verbindung stärken könnte. Zusammenwirkende Zellgruppen könnten Wahrnehmung und Gedächtnis tragen. Das 1949 während seiner Tätigkeit an McGill erschienene Buch verband psychologische Fragen mit biologischen Mechanismen. Es formulierte eine Lernhypothese, keine vollständige Beschreibung synaptischer Plastizität. Spätere mathematische Lernregeln vereinfachten den Vorschlag auf unterschiedliche Weise.',
      'En The Organization of Behavior, Hebb propuso que participar repetidamente en la activación de otra célula podía reforzar una conexión. Grupos de células cooperantes podrían sustentar percepción y memoria. Publicado en 1949 durante su trabajo en McGill, el libro unió preguntas psicológicas y mecanismos biológicos. Planteaba una hipótesis de aprendizaje, no una descripción completa de la plasticidad sináptica. Las reglas matemáticas posteriores simplificaron esta propuesta de distintas maneras.',
    ),
    technical: t(
      'A common abstraction is Δwᵢⱼ ∝ xᵢxⱼ. This correlation rule is a later formalization, not Hebb’s original equation.',
      'Eine verbreitete Abstraktion lautet Δwᵢⱼ ∝ xᵢxⱼ. Diese Korrelationsregel ist eine spätere Formalisierung, nicht Hebbs ursprüngliche Gleichung.',
      'Una abstracción habitual es Δwᵢⱼ ∝ xᵢxⱼ. Esta regla de correlación es una formalización posterior, no una ecuación original de Hebb.',
    ),
    startDate: '1949',
    domain: 'neuroscience',
    locations: [place('Montreal, Canada', 'McGill University', 45.5, -73.58, 1949)],
    people: ['Donald O. Hebb'],
    references: ['hebb-1949', 'hebb-mcgill', 'hopfield-1982'],
    tags: ['learning', 'plasticity', 'memory'],
    status: 'verified',
  },
  {
    id: 'turing',
    demo: 'tape',
    slug: 'turing',
    type: 'person',
    title: t(
      'Turing: computation and intelligence',
      'Turing: Berechnung und Intelligenz',
      'Turing: cálculo e inteligencia',
    ),
    shortDescription: t(
      'A precise account of mechanical computation preceded a practical question about machine intelligence. Turing’s work links mathematical possibility with the problem of evaluating intelligent behavior.',
      'Auf eine präzise Beschreibung mechanischer Berechnung folgte eine praktische Frage zur Maschinenintelligenz. Turings Arbeiten verbinden mathematische Möglichkeiten mit der Bewertung intelligenten Verhaltens.',
      'Una definición precisa del cálculo mecánico precedió a una pregunta práctica sobre inteligencia artificial. Turing conectó la posibilidad matemática con la evaluación del comportamiento inteligente.',
    ),
    description: t(
      'Turing’s 1936 work described abstract machines that follow explicit rules and a universal machine able to simulate them. In 1950, Computing Machinery and Intelligence proposed an imitation game and discussed learning machines. These are different contributions: a definition of computation does not establish what intelligence is. The timeline begins with the mathematical paper and links it to the later debate about how machines might be judged.',
      'Turings Arbeit von 1936 beschrieb abstrakte Maschinen mit expliziten Regeln und eine universelle Maschine, die sie simulieren kann. Computing Machinery and Intelligence stellte 1950 ein Imitationsspiel vor und diskutierte lernende Maschinen. Dies sind unterschiedliche Beiträge: Eine Definition von Berechnung legt nicht fest, was Intelligenz ist. Die Zeitleiste beginnt mit dem mathematischen Artikel und verbindet ihn mit der späteren Debatte über die Beurteilung von Maschinen.',
      'El trabajo de Turing de 1936 describió máquinas abstractas que siguen reglas explícitas y una máquina universal capaz de simularlas. En 1950, Computing Machinery and Intelligence propuso un juego de imitación y discutió máquinas que aprenden. Son aportaciones distintas: definir el cálculo no establece qué es la inteligencia. La cronología parte del artículo matemático y lo conecta con el debate posterior sobre cómo evaluar máquinas.',
    ),
    technical: t(
      'Universality concerns computability, not speed, consciousness or unlimited resources. The imitation game concerns observable interaction.',
      'Universalität betrifft Berechenbarkeit, nicht Geschwindigkeit, Bewusstsein oder unbegrenzte Ressourcen. Das Imitationsspiel betrifft beobachtbare Interaktion.',
      'La universalidad trata de computabilidad, no de velocidad, conciencia o recursos ilimitados. El juego de imitación evalúa interacción observable.',
    ),
    startDate: '1936',
    endDate: '1950',
    domain: 'mathematics',
    locations: [
      place(
        'Cambridge, United Kingdom',
        'King’s College, University of Cambridge',
        52.2,
        0.12,
        1936,
      ),
    ],
    people: ['Alan M. Turing'],
    references: ['turing-1936', 'turing-1950'],
    tags: ['computation', 'logic', 'intelligence'],
    status: 'verified',
    editorialNotes: t(
      '1936 marks submission and the conventional paper date; the journal volume is also dated 1937. The Cambridge marker refers to the mathematical work.',
      '1936 bezeichnet die Einreichung und übliche Datierung; der Zeitschriftenband wird auch auf 1937 datiert. Der Cambridge-Marker gehört zur mathematischen Arbeit.',
      '1936 indica la presentación y fecha habitual del artículo; el volumen también se fecha en 1937. Cambridge corresponde al trabajo matemático.',
    ),
  },
  {
    id: 'von-neumann',
    demo: 'stored-program',
    slug: 'von-neumann',
    type: 'publication',
    title: t('The EDVAC report', 'Der EDVAC-Bericht', 'El informe EDVAC'),
    shortDescription: t(
      'John von Neumann’s report organized a programmable computer into functional parts. It also used an explicit analogy with nervous systems while discussing electronic computing elements.',
      'John von Neumanns Bericht gliederte einen programmierbaren Computer in Funktionsbereiche. Bei der Beschreibung elektronischer Rechenelemente verwendete er auch eine ausdrückliche Analogie zum Nervensystem.',
      'El informe de John von Neumann organizó un ordenador programable en partes funcionales. También empleó una analogía explícita con el sistema nervioso al describir componentes electrónicos.',
    ),
    description: t(
      'The June 1945 First Draft described a computer with arithmetic, control, memory, input and output. It emerged from the EDVAC project at the University of Pennsylvania’s Moore School. Its neural analogy drew on McCulloch and Pitts, but electronic design imposed different constraints. The report is a landmark document in stored-program computing. Its authorship should not be confused with sole invention of the project’s ideas or engineering.',
      'Der First Draft vom Juni 1945 beschrieb einen Computer mit Rechenwerk, Steuerung, Speicher, Ein- und Ausgabe. Er entstand im EDVAC-Projekt der Moore School an der University of Pennsylvania. Seine neuronale Analogie bezog sich auf McCulloch und Pitts, doch die Elektronik stellte andere Anforderungen. Der Bericht ist ein wichtiger Text zur speicherprogrammierbaren Rechentechnik. Seine Autorschaft bedeutet nicht, dass sämtliche Ideen und technischen Lösungen des Projekts von einer Person stammten.',
      'El First Draft de junio de 1945 describió un ordenador con cálculo, control, memoria, entrada y salida. Surgió del proyecto EDVAC de la Moore School de la Universidad de Pensilvania. Su analogía neuronal recurrió a McCulloch y Pitts, aunque el diseño electrónico imponía otras restricciones. Es un documento fundamental de la computación con programas almacenados. Su autoría no implica que todas las ideas y soluciones técnicas procedieran de una sola persona.',
    ),
    technical: t(
      'Instructions are represented in memory. A neural analogy can guide notation without making an electronic computer a biological model.',
      'Befehle werden im Speicher dargestellt. Eine neuronale Analogie kann die Notation prägen, ohne den Computer zu einem biologischen Modell zu machen.',
      'Las instrucciones se representan en memoria. Una analogía neuronal puede orientar la notación sin convertir el ordenador en un modelo biológico.',
    ),
    startDate: '1945-06-30',
    domain: 'computing',
    locations: [
      place(
        'Philadelphia, United States',
        'Moore School, University of Pennsylvania',
        39.95,
        -75.19,
        1945,
      ),
    ],
    people: ['John von Neumann', 'J. Presper Eckert', 'John W. Mauchly', 'Herman Goldstine'],
    references: ['edvac-1945', 'mcculloch-pitts-1943', 'rand-history'],
    tags: ['stored-program', 'computing', 'historical-context'],
    status: 'verified',
  },
  {
    id: 'shannon',
    demo: 'entropy',
    slug: 'shannon',
    type: 'concept',
    title: t(
      'Shannon measures information',
      'Shannon misst Information',
      'Shannon mide la información',
    ),
    shortDescription: t(
      'Communication became a mathematical problem of uncertainty, coding and noise. Shannon’s framework measures information statistically, without claiming to measure a message’s meaning or intelligence.',
      'Kommunikation wurde zu einem mathematischen Problem von Unsicherheit, Kodierung und Rauschen. Shannons Ansatz misst Information statistisch, ohne Bedeutung oder Intelligenz einer Nachricht zu messen.',
      'La comunicación se convirtió en un problema matemático de incertidumbre, codificación y ruido. Shannon mide información estadística, sin pretender medir el significado o la inteligencia de un mensaje.',
    ),
    description: t(
      'Shannon’s 1948 communication theory studied how messages can be represented and transmitted through constrained channels. Entropy quantifies uncertainty about a source; channel capacity concerns reliable transmission. These tools made coding and noise mathematically tractable. Shannon also helped propose the Dartmouth project. His presence connects communication research with early machine intelligence, while the graph keeps information theory distinct from a theory of understanding.',
      'Shannons Kommunikationstheorie von 1948 untersuchte, wie Nachrichten über begrenzte Kanäle dargestellt und übertragen werden. Entropie quantifiziert die Unsicherheit einer Quelle; Kanalkapazität betrifft zuverlässige Übertragung. Damit ließen sich Kodierung und Rauschen mathematisch behandeln. Shannon wirkte auch am Dartmouth-Antrag mit. Seine Beteiligung verbindet Kommunikationsforschung mit früher Maschinenintelligenz; der Graph unterscheidet Informationstheorie jedoch von einer Theorie des Verstehens.',
      'La teoría de comunicación de Shannon de 1948 estudió cómo representar y transmitir mensajes por canales limitados. La entropía cuantifica la incertidumbre de una fuente; la capacidad del canal describe la transmisión fiable. Estas herramientas permitieron tratar matemáticamente la codificación y el ruido. Shannon también participó en la propuesta de Dartmouth. Su presencia conecta comunicación e inteligencia artificial temprana, sin convertir la teoría de información en una teoría de la comprensión.',
    ),
    technical: t(
      'For discrete outcomes, H(X) = −Σ p(x) log₂ p(x), measured in bits. Statistical uncertainty and semantic meaning are different questions.',
      'Für diskrete Ergebnisse gilt H(X) = −Σ p(x) log₂ p(x), gemessen in Bits. Statistische Unsicherheit und Bedeutung sind verschiedene Fragen.',
      'Para resultados discretos, H(X) = −Σ p(x) log₂ p(x), en bits. Incertidumbre estadística y significado son cuestiones distintas.',
    ),
    startDate: '1948',
    domain: 'mathematics',
    locations: [],
    people: ['Claude E. Shannon'],
    references: ['shannon-1948', 'dartmouth-proposal'],
    tags: ['information', 'entropy', 'communication'],
    status: 'verified',
    editorialNotes: t(
      'Bell Telephone Laboratories is documented; no exact 1948 office location is asserted.',
      'Bell Telephone Laboratories ist belegt; ein genauer Bürostandort für 1948 wird nicht behauptet.',
      'Está documentada la vinculación a Bell Telephone Laboratories; no se afirma una oficina exacta en 1948.',
    ),
  },
  {
    id: 'cybernetics',
    demo: 'feedback',
    slug: 'cybernetics',
    type: 'field',
    title: t('Wiener and cybernetics', 'Wiener und die Kybernetik', 'Wiener y la cibernética'),
    shortDescription: t(
      'Feedback offered a shared language for studying animals and machines. Cybernetics connected communication and control, bringing biological regulation into conversation with engineering and mathematics.',
      'Rückkopplung bot eine gemeinsame Sprache für Tiere und Maschinen. Die Kybernetik verband Kommunikation und Regelung und brachte biologische Regulation mit Technik und Mathematik ins Gespräch.',
      'La retroalimentación ofreció un lenguaje común para animales y máquinas. La cibernética conectó comunicación y control, relacionando regulación biológica, ingeniería y matemáticas.',
    ),
    description: t(
      'Norbert Wiener’s 1948 book made cybernetics an influential interdisciplinary framework. A system could respond to information about its own behavior, rather than merely follow an open sequence of commands. The comparison invited researchers to study shared principles of regulation. This is historical context for later machine intelligence, not evidence that all cybernetic systems learn or that every feedback controller models a brain.',
      'Norbert Wieners Buch von 1948 machte die Kybernetik zu einem einflussreichen interdisziplinären Ansatz. Ein System konnte auf Informationen über sein eigenes Verhalten reagieren, statt nur eine offene Befehlsfolge abzuarbeiten. Der Vergleich regte die Suche nach gemeinsamen Regelungsprinzipien an. Dies ist historischer Kontext späterer Maschinenintelligenz, aber kein Beleg dafür, dass alle kybernetischen Systeme lernen oder jeder Rückkopplungsregler ein Gehirn modelliert.',
      'El libro de Norbert Wiener de 1948 convirtió la cibernética en un marco interdisciplinario influyente. Un sistema podía responder a información sobre su propio comportamiento, en lugar de seguir una secuencia abierta de órdenes. La comparación invitó a investigar principios compartidos de regulación. Aporta contexto histórico a la inteligencia artificial posterior, sin demostrar que todo sistema cibernético aprenda ni que cada controlador modele un cerebro.',
    ),
    technical: t(
      'In a feedback loop, measured output influences future input. Stability, delay and noise affect the resulting behavior.',
      'In einer Rückkopplung beeinflusst der gemessene Ausgang künftige Eingaben. Stabilität, Verzögerung und Rauschen prägen das Verhalten.',
      'En un bucle de retroalimentación, la salida medida influye en la entrada futura. Estabilidad, demora y ruido afectan al comportamiento.',
    ),
    startDate: '1948',
    domain: 'mathematics',
    locations: [
      place(
        'Cambridge, United States',
        'Massachusetts Institute of Technology',
        42.36,
        -71.09,
        1948,
      ),
    ],
    people: ['Norbert Wiener'],
    references: ['wiener-1948', 'dartmouth-recollection'],
    tags: ['feedback', 'control', 'communication'],
    status: 'verified',
  },
  {
    id: 'dartmouth',
    slug: 'dartmouth',
    type: 'event',
    title: t(
      'The Dartmouth summer project',
      'Das Dartmouth-Sommerprojekt',
      'El proyecto de verano de Dartmouth',
    ),
    shortDescription: t(
      'A 1955 proposal named artificial intelligence as a research project for summer 1956. Its agenda included language, abstraction, learning and networks of hypothetical computational units.',
      'Ein Antrag von 1955 benannte künstliche Intelligenz als Forschungsprojekt für den Sommer 1956. Sprache, Abstraktion, Lernen und Netze hypothetischer Recheneinheiten gehörten zum Programm.',
      'Una propuesta de 1955 presentó la inteligencia artificial como proyecto para el verano de 1956. Su programa incluía lenguaje, abstracción, aprendizaje y redes de unidades computacionales hipotéticas.',
    ),
    description: t(
      'John McCarthy, Marvin Minsky, Nathaniel Rochester and Claude Shannon proposed a summer study at Dartmouth College. Their optimism helped establish a recognizable research agenda, but the meeting did not create every underlying idea. McCarthy later recalled that participants arrived for different lengths of time and pursued their own interests. The proposal included both symbolic questions and networks, complicating a simple story of two separate traditions.',
      'John McCarthy, Marvin Minsky, Nathaniel Rochester und Claude Shannon schlugen eine Sommerstudie am Dartmouth College vor. Ihr Optimismus trug zu einem erkennbaren Forschungsprogramm bei, doch die Tagung schuf nicht sämtliche zugrunde liegenden Ideen. McCarthy erinnerte sich später an unterschiedlich lange Aufenthalte und eigene Interessen der Teilnehmer. Der Antrag umfasste symbolische Fragen ebenso wie Netze und widerspricht damit einer einfachen Geschichte zweier getrennter Traditionen.',
      'John McCarthy, Marvin Minsky, Nathaniel Rochester y Claude Shannon propusieron un estudio de verano en Dartmouth College. Su optimismo ayudó a establecer un programa reconocible, pero la reunión no creó todas sus ideas previas. McCarthy recordó después que los participantes permanecieron durante períodos distintos y siguieron sus propios intereses. La propuesta incluía preguntas simbólicas y redes, lo que complica una historia de dos tradiciones completamente separadas.',
    ),
    technical: t(
      'The original proposal is dated August 31, 1955. The timeline marks the 1956 research meeting, not the proposal’s publication.',
      'Der Originalantrag trägt das Datum 31. August 1955. Die Zeitleiste markiert die Forschungstagung von 1956, nicht den Antrag.',
      'La propuesta original está fechada el 31 de agosto de 1955. La cronología señala la reunión de 1956, no la propuesta.',
    ),
    startDate: '1956',
    domain: 'computing',
    locations: [place('Hanover, United States', 'Dartmouth College', 43.7, -72.29, 1956)],
    people: ['John McCarthy', 'Marvin Minsky', 'Nathaniel Rochester', 'Claude Shannon'],
    references: ['dartmouth-proposal', 'dartmouth-recollection'],
    tags: ['institutions', 'symbolic-reasoning', 'learning'],
    status: 'verified',
  },
  {
    id: 'symbolic-ai',
    demo: 'symbolic',
    slug: 'symbolic-ai',
    type: 'algorithm',
    title: t(
      'Logic Theorist and symbolic reasoning',
      'Logic Theorist und symbolisches Schlussfolgern',
      'Logic Theorist y razonamiento simbólico',
    ),
    shortDescription: t(
      'Programs could search through symbolic expressions and construct proofs. Logic Theorist made heuristic reasoning a concrete computational object, alongside the emerging study of trainable networks.',
      'Programme konnten symbolische Ausdrücke durchsuchen und Beweise konstruieren. Logic Theorist machte heuristisches Schlussfolgern zu einem konkreten Rechenverfahren neben der entstehenden Forschung an trainierbaren Netzen.',
      'Los programas podían explorar expresiones simbólicas y construir demostraciones. Logic Theorist convirtió el razonamiento heurístico en un procedimiento computacional, junto al estudio emergente de redes entrenables.',
    ),
    description: t(
      'Allen Newell, Herbert Simon and Cliff Shaw collaborated on the Logic Theorist at RAND and Carnegie. Their 1956 account described a system for finding proofs using heuristics that narrowed the search. Symbolic expressions made rules and intermediate steps explicit. This approach addressed a different task from perceptual classification. Its historical importance does not require treating symbolic reasoning as a failed detour on the way to neural networks.',
      'Allen Newell, Herbert Simon und Cliff Shaw arbeiteten bei RAND und Carnegie am Logic Theorist. Die Darstellung von 1956 beschrieb ein System, das Beweise mit suchraumbeschränkenden Heuristiken fand. Symbolische Ausdrücke machten Regeln und Zwischenschritte explizit. Dieser Ansatz bearbeitete eine andere Aufgabe als Wahrnehmungsklassifikation. Seine historische Bedeutung verlangt nicht, symbolisches Schlussfolgern als gescheiterten Umweg auf dem Weg zu neuronalen Netzen darzustellen.',
      'Allen Newell, Herbert Simon y Cliff Shaw colaboraron en Logic Theorist en RAND y Carnegie. Su descripción de 1956 presentó un sistema para encontrar demostraciones mediante heurísticas que reducían la búsqueda. Las expresiones simbólicas hacían explícitas las reglas y los pasos intermedios. Este enfoque abordaba una tarea distinta de la clasificación perceptiva. Su importancia histórica no exige presentar el razonamiento simbólico como un desvío fallido hacia las redes neuronales.',
    ),
    technical: t(
      'Heuristic search selects promising proof steps. It trades exhaustive enumeration for rules that make a particular problem tractable.',
      'Heuristische Suche wählt aussichtsreiche Beweisschritte. Sie ersetzt vollständige Aufzählung durch Regeln, die ein bestimmtes Problem handhabbar machen.',
      'La búsqueda heurística selecciona pasos prometedores. Sustituye la enumeración exhaustiva por reglas que vuelven abordable un problema concreto.',
    ),
    startDate: '1956',
    domain: 'computing',
    locations: [
      place('Santa Monica, United States', 'RAND Corporation', 34.01, -118.49, 1956),
      place('Pittsburgh, United States', 'Carnegie Institute of Technology', 40.44, -79.94, 1956),
    ],
    people: ['Allen Newell', 'Herbert A. Simon', 'Cliff Shaw'],
    references: ['logic-theory-1956', 'rand-history'],
    tags: ['logic', 'search', 'symbolic-reasoning'],
    status: 'verified',
  },
  {
    id: 'perceptrons-1969',
    demo: 'xor',
    slug: 'perceptrons-1969',
    type: 'publication',
    title: t(
      'Perceptrons: the scope of a limitation',
      'Perceptrons: die Reichweite einer Grenze',
      'Perceptrons: el alcance de una limitación',
    ),
    shortDescription: t(
      'Minsky and Papert analyzed restricted classes of perceptrons. Their mathematical results matter, but extending them to every neural architecture or assigning them sole responsibility for funding changes misreads their scope.',
      'Minsky und Papert analysierten eingeschränkte Klassen von Perzeptronen. Ihre mathematischen Ergebnisse sind wichtig; sie gelten jedoch nicht für jede Netzarchitektur und erklären Förderveränderungen nicht allein.',
      'Minsky y Papert analizaron clases restringidas de perceptrones. Sus resultados son importantes, pero no abarcan todas las arquitecturas neuronales ni explican por sí solos los cambios de financiación.',
    ),
    description: t(
      'Perceptrons appeared in 1969 as a study of computational geometry and limitations of particular architectures. The familiar XOR example illustrates the limits of a single linear threshold unit on its original inputs. It does not show that multilayer networks cannot represent XOR. Claims about the book’s wider historical consequences require different evidence from its mathematical results. Those disputed interpretations are explored separately in the AI winters node.',
      'Perceptrons erschien 1969 als Untersuchung der rechnerischen Geometrie und Grenzen bestimmter Architekturen. Das bekannte XOR-Beispiel zeigt die Grenze einer einzelnen linearen Schwellwerteinheit mit ursprünglichen Eingaben. Es beweist nicht, dass mehrschichtige Netze XOR nicht darstellen können. Aussagen über die weiteren historischen Folgen des Buchs benötigen andere Belege als mathematische Resultate. Diese umstrittenen Deutungen behandelt der eigene Knoten zu den KI-Wintern.',
      'Perceptrons apareció en 1969 como estudio de geometría computacional y límites de ciertas arquitecturas. El ejemplo habitual de XOR muestra la limitación de una sola unidad de umbral lineal con sus entradas originales. No demuestra que las redes multicapa sean incapaces de representar XOR. Las consecuencias históricas del libro requieren pruebas distintas de sus resultados matemáticos. El nodo de los inviernos de la IA aborda esas interpretaciones discutidas.',
    ),
    technical: t(
      'Representational limits depend on the permitted architecture and features. A theorem’s assumptions are part of its conclusion.',
      'Darstellungsgrenzen hängen von erlaubter Architektur und Merkmalen ab. Die Voraussetzungen eines Satzes gehören zu seiner Aussage.',
      'Los límites de representación dependen de la arquitectura y las características permitidas. Las hipótesis de un teorema forman parte de su alcance.',
    ),
    startDate: '1969',
    domain: 'mathematics',
    locations: [
      place(
        'Cambridge, United States',
        'Massachusetts Institute of Technology',
        42.36,
        -71.09,
        1969,
      ),
    ],
    people: ['Marvin Minsky', 'Seymour Papert'],
    references: ['minsky-papert-1969', 'perceptron-course', 'haigh-2023'],
    tags: ['limitations', 'linear-classification', 'historical-debate'],
    status: 'verified',
  },
  {
    id: 'ai-winters',
    slug: 'ai-winters',
    type: 'event',
    title: t(
      'AI winters: a contested history',
      'KI-Winter: eine umstrittene Geschichte',
      'Inviernos de la IA: una historia discutida',
    ),
    shortDescription: t(
      'Research criticism, funding decisions and commercial disappointment did not unfold uniformly. The familiar winter metaphor can hide continuing work and differences between countries, institutions and research traditions.',
      'Forschungskritik, Förderentscheidungen und kommerzielle Enttäuschungen verliefen nicht einheitlich. Die Wintermetapher kann fortgesetzte Forschung und Unterschiede zwischen Ländern, Institutionen und Forschungstraditionen verdecken.',
      'Las críticas, las decisiones de financiación y las decepciones comerciales no siguieron un patrón uniforme. La metáfora del invierno puede ocultar investigación continuada y diferencias entre países e instituciones.',
    ),
    description: t(
      'The 1973 publication of the Lighthill report is one landmark in debates about research promises and public support. Later accounts often group several setbacks into first and second AI winters. Historians question both the boundaries and the explanatory value of that story. Jon Agar situates Lighthill within debates about practical usefulness; Thomas Haigh contests a general first winter. No single book or funding decision explains every research community’s trajectory.',
      'Die Veröffentlichung des Lighthill-Berichts 1973 ist ein Bezugspunkt der Debatte über Forschungsversprechen und öffentliche Förderung. Spätere Darstellungen bündeln mehrere Rückschläge oft zu einem ersten und zweiten KI-Winter. Historiker hinterfragen sowohl die Grenzen als auch den Erklärungswert dieser Erzählung. Jon Agar ordnet Lighthill in Debatten über praktische Nützlichkeit ein; Thomas Haigh bestreitet einen allgemeinen ersten Winter. Kein einzelnes Buch erklärt die Entwicklung sämtlicher Forschungsgemeinschaften.',
      'La publicación del informe Lighthill en 1973 es un hito del debate sobre promesas científicas y apoyo público. Relatos posteriores agrupan varios retrocesos en un primer y segundo invierno de la IA. Los historiadores cuestionan los límites y el valor explicativo de esa narrativa. Jon Agar sitúa a Lighthill en debates sobre utilidad práctica; Thomas Haigh cuestiona un primer invierno general. Ningún libro explica la trayectoria de todas las comunidades científicas.',
    ),
    technical: t(
      'This date range is an editorial grouping of debates and setbacks, not one continuous worldwide cessation of research.',
      'Dieser Zeitraum ist eine redaktionelle Gruppierung von Debatten und Rückschlägen, kein weltweiter, durchgehender Forschungsstillstand.',
      'Este intervalo agrupa debates y retrocesos editorialmente; no representa una interrupción mundial y continua de la investigación.',
    ),
    startDate: '1973',
    endDate: '1993',
    domain: 'computing',
    locations: [],
    people: ['James Lighthill', 'Marvin Minsky', 'Seymour Papert'],
    references: ['agar-2020', 'haigh-2023', 'minsky-papert-1969'],
    tags: ['funding', 'historical-context', 'historical-debate'],
    status: 'historically-disputed',
    editorialNotes: t(
      'The winter metaphor, causal interpretation and period boundaries are disputed. The 1973–1993 range is approximate and must not be read as a single event.',
      'Wintermetapher, Ursachen und Periodengrenzen sind umstritten. Der ungefähre Zeitraum 1973–1993 bezeichnet kein einzelnes Ereignis.',
      'Se discuten la metáfora, las causas y los límites temporales. El intervalo aproximado 1973–1993 no representa un único acontecimiento.',
    ),
  },
  {
    id: 'hopfield',
    demo: 'memory',
    slug: 'hopfield',
    type: 'architecture',
    title: t(
      'Hopfield: memory as a stable state',
      'Hopfield: Gedächtnis als stabiler Zustand',
      'Hopfield: memoria como estado estable',
    ),
    shortDescription: t(
      'A recurrent network can recover a stored pattern from an incomplete cue. Hopfield connected collective behavior in physical systems with a mathematical model of associative memory.',
      'Ein rekurrentes Netz kann ein gespeichertes Muster aus einem unvollständigen Hinweis rekonstruieren. Hopfield verband kollektives Verhalten physikalischer Systeme mit einem mathematischen Modell des Assoziativgedächtnisses.',
      'Una red recurrente puede recuperar un patrón almacenado a partir de una pista incompleta. Hopfield conectó el comportamiento colectivo de sistemas físicos con un modelo matemático de memoria asociativa.',
    ),
    description: t(
      'Hopfield’s 1982 paper showed how interacting artificial units could collectively retrieve patterns. With suitable symmetric connections, asynchronous updates settle toward stable states. A partial or corrupted pattern can therefore lead to a stored memory, although retrieval can fail. The paper’s affiliations were Caltech and Bell Laboratories. The 2024 Physics Nobel jointly recognized Hopfield and Hinton for foundational work enabling machine learning with artificial neural networks.',
      'Hopfields Artikel von 1982 zeigte, wie wechselwirkende künstliche Einheiten gemeinsam Muster abrufen können. Bei geeigneten symmetrischen Verbindungen führen asynchrone Aktualisierungen zu stabilen Zuständen. Ein unvollständiges oder gestörtes Muster kann so eine gespeicherte Erinnerung erreichen, wobei der Abruf auch scheitern kann. Der Artikel nennt Caltech und Bell Laboratories. Der Physiknobelpreis 2024 würdigte Hopfield und Hinton gemeinsam für grundlegende Beiträge zum maschinellen Lernen mit künstlichen neuronalen Netzen.',
      'El artículo de Hopfield de 1982 mostró cómo unidades artificiales interconectadas podían recuperar patrones colectivamente. Con conexiones simétricas adecuadas, las actualizaciones asíncronas llevan a estados estables. Un patrón parcial o alterado puede conducir a una memoria almacenada, aunque la recuperación puede fallar. El artículo indicaba afiliaciones a Caltech y Bell Laboratories. El Nobel de Física de 2024 reconoció conjuntamente a Hopfield y Hinton por contribuciones fundamentales al aprendizaje con redes artificiales.',
    ),
    technical: t(
      'A decreasing energy function explains convergence under specific update assumptions. Stable attractors can include unintended patterns.',
      'Eine abnehmende Energiefunktion erklärt Konvergenz unter bestimmten Aktualisierungsannahmen. Stabile Attraktoren können auch unerwünschte Muster sein.',
      'Una función de energía decreciente explica la convergencia bajo ciertas reglas. Los atractores estables pueden incluir patrones no deseados.',
    ),
    startDate: '1982',
    domain: 'learning',
    locations: [
      place('Pasadena, United States', 'California Institute of Technology', 34.14, -118.13, 1982),
      place('Murray Hill, United States', 'Bell Laboratories', 40.68, -74.4, 1982),
    ],
    people: ['John J. Hopfield'],
    references: ['hopfield-1982', 'hebb-1949', 'nobel-physics-2024'],
    tags: ['memory', 'recurrence', 'energy'],
    status: 'verified',
    nobel: {
      year: 2024,
      reference: 'nobel-physics-2024',
      label: t(
        'Physics 2024: John Hopfield and Geoffrey Hinton, jointly',
        'Physik 2024: John Hopfield und Geoffrey Hinton, gemeinsam',
        'Física 2024: John Hopfield y Geoffrey Hinton, conjuntamente',
      ),
    },
  },
  {
    id: 'mnist',
    demo: 'digits',
    slug: 'mnist',
    type: 'dataset',
    title: t(
      'MNIST: a shared digit benchmark',
      'MNIST: ein gemeinsamer Ziffern-Benchmark',
      'MNIST: un referente común de dígitos',
    ),
    shortDescription: t(
      'A carefully prepared collection of handwritten digits made learning algorithms easier to compare. Shared examples and a held-out test set became part of the experimental infrastructure.',
      'Ein sorgfältig aufbereiteter Datensatz handgeschriebener Ziffern erleichterte den Vergleich von Lernverfahren. Gemeinsame Beispiele und ein separater Testsatz wurden Teil der experimentellen Infrastruktur.',
      'Una colección preparada de dígitos manuscritos facilitó comparar algoritmos. Ejemplos comunes y un conjunto de prueba separado pasaron a formar parte de la infraestructura experimental.',
    ),
    description: t(
      'MNIST contains 60,000 training images and 10,000 test images derived from NIST handwriting data. Digits are normalized and centered in small images, reducing preprocessing work for researchers. The 1998 document-recognition paper provides the milestone used here. A benchmark isolates a useful task; success on these digits does not establish general visual understanding. The dataset’s role belongs alongside the algorithms that were evaluated on it.',
      'MNIST enthält 60.000 Trainings- und 10.000 Testbilder aus NIST-Handschriftdaten. Die Ziffern sind normalisiert und in kleinen Bildern zentriert, was Forschenden Vorverarbeitung erspart. Der Artikel zur Dokumenterkennung von 1998 dient hier als Meilenstein. Ein Benchmark grenzt eine nützliche Aufgabe ab; Erfolg auf diesen Ziffern belegt kein allgemeines visuelles Verständnis. Die Rolle des Datensatzes gehört neben die darauf bewerteten Algorithmen.',
      'MNIST contiene 60.000 imágenes de entrenamiento y 10.000 de prueba derivadas de datos manuscritos de NIST. Los dígitos están normalizados y centrados en imágenes pequeñas, reduciendo el preprocesamiento. El artículo de reconocimiento documental de 1998 aporta el hito usado aquí. Un referente delimita una tarea útil; acertar estos dígitos no demuestra comprensión visual general. El conjunto de datos merece atención junto a los algoritmos evaluados con él.',
    ),
    technical: t(
      'Images are 28 × 28 grayscale pixels. Training and test examples have different roles; tuning repeatedly on the test set compromises evaluation.',
      'Die Bilder haben 28 × 28 Graustufenpixel. Training und Test erfüllen verschiedene Rollen; wiederholte Testoptimierung beeinträchtigt die Bewertung.',
      'Las imágenes tienen 28 × 28 píxeles en gris. Entrenamiento y prueba cumplen funciones distintas; ajustar repetidamente al test perjudica la evaluación.',
    ),
    startDate: '1998',
    domain: 'computing',
    locations: [],
    people: ['Yann LeCun', 'Corinna Cortes', 'Christopher J. C. Burges'],
    references: ['mnist-creators', 'lecun-1998'],
    tags: ['datasets', 'handwriting', 'benchmarks'],
    status: 'verified',
    editorialNotes: t(
      'The date marks the cited 1998 benchmark account. Current affiliations on the dataset website are not used as historical locations.',
      'Das Datum bezeichnet die zitierte Benchmark-Darstellung von 1998. Aktuelle Zugehörigkeiten der Website werden nicht als historische Orte verwendet.',
      'La fecha señala la descripción de 1998. Las afiliaciones actuales de la web no se utilizan como ubicaciones históricas.',
    ),
  },
  {
    id: 'bellman',
    demo: 'planning',
    slug: 'bellman',
    type: 'concept',
    title: t(
      'Bellman and dynamic programming',
      'Bellman und dynamische Programmierung',
      'Bellman y la programación dinámica',
    ),
    shortDescription: t(
      'Long sequences of decisions can be analyzed through smaller recurring problems. Bellman’s mathematical framework supplied a foundation for later methods that learn the value of actions from experience.',
      'Lange Entscheidungsfolgen lassen sich durch kleinere, wiederkehrende Probleme analysieren. Bellmans mathematischer Rahmen schuf eine Grundlage für spätere Verfahren, die Handlungswerte aus Erfahrung lernen.',
      'Las secuencias largas de decisiones pueden analizarse mediante problemas menores recurrentes. El marco de Bellman fundamentó métodos posteriores que aprenden el valor de las acciones a partir de la experiencia.',
    ),
    description: t(
      'Bellman’s 1957 book consolidated dynamic programming for multistage decisions. A good decision depends on both its immediate consequences and the best continuation from the resulting situation. Working at RAND, he developed a mathematical approach with applications beyond learning. Reinforcement learning later combined related value recursions with sampled experience. Dynamic programming itself can instead assume a known model of transitions and outcomes.',
      'Bellmans Buch von 1957 bündelte dynamische Programmierung für mehrstufige Entscheidungen. Eine gute Entscheidung hängt von unmittelbaren Folgen und der besten Fortsetzung aus der entstehenden Situation ab. Bei RAND entwickelte er einen mathematischen Ansatz mit Anwendungen über Lernen hinaus. Später verband verstärkendes Lernen verwandte Wertrekursionen mit Stichproben aus Erfahrung. Dynamische Programmierung kann dagegen ein bekanntes Modell der Übergänge und Ergebnisse voraussetzen.',
      'El libro de Bellman de 1957 consolidó la programación dinámica para decisiones sucesivas. Una buena decisión depende tanto de sus consecuencias inmediatas como de la mejor continuación desde la situación resultante. En RAND desarrolló un enfoque matemático con aplicaciones más allá del aprendizaje. El aprendizaje por refuerzo combinó después recurrencias de valor similares con experiencia muestreada. La programación dinámica puede, en cambio, partir de un modelo conocido de transiciones y resultados.',
    ),
    technical: t(
      'A value recursion combines immediate reward with expected future value. The state must contain the information needed for that recursion.',
      'Eine Wertrekursion verbindet unmittelbare Belohnung mit erwartetem Folgewert. Der Zustand muss die dafür nötigen Informationen enthalten.',
      'Una recurrencia de valor combina recompensa inmediata y valor futuro esperado. El estado debe contener la información necesaria.',
    ),
    startDate: '1957',
    domain: 'mathematics',
    locations: [place('Santa Monica, United States', 'RAND Corporation', 34.01, -118.49, 1957)],
    people: ['Richard Bellman'],
    references: ['bellman-1957', 'bellman-communication', 'watkins-dayan-1992'],
    tags: ['reinforcement-learning', 'planning', 'value'],
    status: 'verified',
  },
  {
    id: 'temporal-difference',
    demo: 'reward',
    slug: 'temporal-difference',
    type: 'algorithm',
    title: t(
      'Learning from changing predictions',
      'Aus veränderten Vorhersagen lernen',
      'Aprender de predicciones cambiantes',
    ),
    shortDescription: t(
      'A learner need not wait for the final outcome before updating a prediction. Temporal-difference methods use changes in successive estimates to distribute learning through time.',
      'Ein Lernverfahren muss nicht auf das Endergebnis warten, um eine Vorhersage anzupassen. Temporal-Difference-Verfahren nutzen Veränderungen aufeinanderfolgender Schätzungen und verteilen Lernen über die Zeit.',
      'Un sistema no necesita esperar al resultado final para actualizar una predicción. Los métodos de diferencias temporales utilizan cambios entre estimaciones sucesivas para distribuir el aprendizaje en el tiempo.',
    ),
    description: t(
      'Sutton’s 1988 paper gave a systematic treatment of learning from differences between successive predictions. It explicitly acknowledged earlier related methods, including Samuel’s checkers work and adaptive critic research. The approach became central to reinforcement learning and later to computational accounts of reward signals in the brain. The paper was written at GTE Laboratories in Waltham, a reminder that this lineage crossed university and industrial laboratories.',
      'Suttons Artikel von 1988 behandelte Lernen aus Unterschieden aufeinanderfolgender Vorhersagen systematisch. Er würdigte ausdrücklich frühere verwandte Verfahren, darunter Samuels Damespiel und Forschung zu adaptiven Kritikern. Der Ansatz wurde zentral für verstärkendes Lernen und später für rechnerische Erklärungen von Belohnungssignalen im Gehirn. Die Arbeit entstand bei GTE Laboratories in Waltham; diese Entwicklung verlief also über Hochschulen und industrielle Forschungslabore hinweg.',
      'El artículo de Sutton de 1988 estudió sistemáticamente el aprendizaje a partir de diferencias entre predicciones sucesivas. Reconocía métodos anteriores, como las damas de Samuel y los críticos adaptativos. El enfoque se volvió central para el aprendizaje por refuerzo y después para explicar computacionalmente señales de recompensa cerebrales. El artículo se realizó en GTE Laboratories, en Waltham, mostrando una trayectoria que atravesó universidades y laboratorios industriales.',
    ),
    technical: t(
      'A common error is δ = r + γV(s′) − V(s). Bootstrapping updates an estimate using another estimate.',
      'Ein üblicher Fehler lautet δ = r + γV(s′) − V(s). Bootstrapping aktualisiert eine Schätzung mithilfe einer anderen.',
      'Un error habitual es δ = r + γV(s′) − V(s). El bootstrapping actualiza una estimación utilizando otra.',
    ),
    startDate: '1988',
    domain: 'learning',
    locations: [place('Waltham, United States', 'GTE Laboratories', 42.4, -71.26, 1988)],
    people: ['Richard S. Sutton', 'Andrew G. Barto'],
    references: ['sutton-1988', 'schultz-dayan-montague-1997'],
    tags: ['reinforcement-learning', 'prediction', 'reward'],
    status: 'verified',
  },
  {
    id: 'q-learning',
    demo: 'q-update',
    slug: 'q-learning',
    type: 'algorithm',
    title: t(
      'Q-learning values possible actions',
      'Q-Lernen bewertet mögliche Handlungen',
      'Q-learning valora acciones posibles',
    ),
    shortDescription: t(
      'Learning action values offers a route from experience to better choices. Q-learning updates estimates from observed transitions without requiring a complete model of the environment.',
      'Das Lernen von Handlungswerten führt von Erfahrung zu besseren Entscheidungen. Q-Lernen aktualisiert Schätzungen aus beobachteten Übergängen, ohne ein vollständiges Umgebungsmodell vorauszusetzen.',
      'Aprender valores de acciones permite mejorar decisiones con la experiencia. Q-learning actualiza estimaciones mediante transiciones observadas, sin exigir un modelo completo del entorno.',
    ),
    description: t(
      'Watkins introduced Q-learning in his 1989 doctoral work. The 1992 paper with Dayan established a convergence result for discrete action values under appropriate sampling and learning conditions. The algorithm connects temporal-difference updates with dynamic programming’s optimality principle. Its guarantee is conditional: it does not automatically cover a deep network, finite training, or a changing environment. These distinctions matter when following the later path to DQN.',
      'Watkins führte Q-Lernen in seiner Dissertation von 1989 ein. Der Artikel mit Dayan von 1992 zeigte Konvergenz für diskrete Handlungswerte unter geeigneten Stichproben- und Lernbedingungen. Der Algorithmus verbindet Temporal-Difference-Aktualisierungen mit dem Optimalitätsprinzip der dynamischen Programmierung. Die Garantie ist bedingt: Sie umfasst nicht automatisch tiefe Netze, begrenztes Training oder veränderliche Umgebungen. Diese Unterschiede sind für die spätere Entwicklung zu DQN wichtig.',
      'Watkins presentó Q-learning en su tesis de 1989. El artículo con Dayan de 1992 demostró convergencia para valores discretos bajo condiciones adecuadas de muestreo y aprendizaje. El algoritmo conecta actualizaciones por diferencias temporales con el principio de optimalidad de programación dinámica. La garantía es condicional: no cubre automáticamente redes profundas, entrenamiento finito ni entornos cambiantes. Estas diferencias importan al seguir su evolución hacia DQN.',
    ),
    technical: t(
      'The target r + γ maxₐ Q(s′, a) estimates the return of a greedy continuation. Exploration must still provide useful samples.',
      'Das Ziel r + γ maxₐ Q(s′, a) schätzt den Ertrag einer gierigen Fortsetzung. Exploration muss weiterhin geeignete Stichproben liefern.',
      'El objetivo r + γ maxₐ Q(s′, a) estima el retorno de una continuación voraz. La exploración debe aportar muestras útiles.',
    ),
    startDate: '1992',
    domain: 'learning',
    locations: [
      place(
        'Edinburgh, United Kingdom',
        'Centre for Cognitive Science, University of Edinburgh',
        55.95,
        -3.19,
        1992,
      ),
    ],
    people: ['Christopher J. C. H. Watkins', 'Peter Dayan'],
    references: ['watkins-dayan-1992', 'sutton-1988', 'dqn-2015'],
    tags: ['reinforcement-learning', 'value', 'exploration'],
    status: 'verified',
    editorialNotes: t(
      'The date marks the joint paper; Watkins’s thesis dates to 1989. The map marks Dayan’s listed affiliation, not a shared laboratory.',
      'Das Datum bezeichnet den gemeinsamen Artikel; Watkins’ Dissertation stammt von 1989. Die Karte zeigt Dayans angegebene Institution, kein gemeinsames Labor.',
      'La fecha corresponde al artículo conjunto; la tesis de Watkins es de 1989. El mapa muestra la afiliación de Dayan, no un laboratorio compartido.',
    ),
  },
  {
    id: 'dopamine',
    demo: 'surprise',
    slug: 'dopamine',
    type: 'publication',
    title: t(
      'Dopamine and reward prediction error',
      'Dopamin und Belohnungsvorhersagefehler',
      'Dopamina y error de predicción de recompensa',
    ),
    shortDescription: t(
      'Computational learning theory helped interpret biological recordings. Changes in some dopamine signals resembled an error between expected and obtained reward, connecting reinforcement learning back to neuroscience.',
      'Rechnerische Lerntheorie half bei der Deutung biologischer Messungen. Veränderungen bestimmter Dopaminsignale ähnelten einem Fehler zwischen erwarteter und erhaltener Belohnung und verbanden verstärkendes Lernen mit Neurowissenschaft.',
      'La teoría computacional del aprendizaje ayudó a interpretar registros biológicos. Algunos cambios de dopamina se parecían a un error entre recompensa esperada y obtenida, conectando refuerzo y neurociencia.',
    ),
    description: t(
      'Schultz, Dayan and Montague’s 1997 synthesis connected dopamine recordings with temporal-difference learning. Responses to unexpected rewards, predictive cues and omitted rewards could be interpreted through changing expectations. This is a particularly clear direction of influence from computational theory to neuroscience. The proposed correspondence concerns particular signals and experimental conditions; it should not be expanded into a claim that all dopamine activity or all learning implements one algorithm.',
      'Die Synthese von Schultz, Dayan und Montague von 1997 verband Dopaminmessungen mit Temporal-Difference-Lernen. Reaktionen auf unerwartete Belohnungen, vorhersagende Reize und ausbleibende Belohnungen ließen sich über veränderte Erwartungen deuten. Hier beeinflusste rechnerische Theorie besonders deutlich die Neurowissenschaft. Die vorgeschlagene Entsprechung betrifft bestimmte Signale und Versuchsbedingungen; daraus folgt nicht, dass jede Dopaminaktivität oder jedes Lernen einen einzigen Algorithmus umsetzt.',
      'La síntesis de Schultz, Dayan y Montague de 1997 conectó registros de dopamina con aprendizaje por diferencias temporales. Las respuestas a recompensas inesperadas, señales predictivas y recompensas omitidas podían interpretarse mediante expectativas cambiantes. Es un ejemplo claro de influencia de teoría computacional sobre neurociencia. La correspondencia propuesta afecta a señales y condiciones concretas; no implica que toda actividad dopaminérgica o todo aprendizaje implemente un único algoritmo.',
    ),
    technical: t(
      'A prediction error is a difference from expectation, not simply the amount of reward. A fully predicted reward can produce little error.',
      'Ein Vorhersagefehler ist eine Abweichung von der Erwartung, nicht einfach die Belohnungsmenge. Erwartete Belohnung kann wenig Fehler erzeugen.',
      'El error de predicción es una diferencia respecto a lo esperado, no la cantidad de recompensa. Una recompensa prevista puede generar poco error.',
    ),
    startDate: '1997',
    domain: 'neuroai',
    locations: [
      place('Fribourg, Switzerland', 'University of Fribourg', 46.8, 7.15, 1997),
      place('Houston, United States', 'Baylor College of Medicine', 29.71, -95.4, 1997),
    ],
    people: ['Wolfram Schultz', 'Peter Dayan', 'P. Read Montague'],
    references: ['schultz-dayan-montague-1997', 'sutton-1988'],
    tags: ['dopamine', 'prediction', 'reinforcement-learning'],
    status: 'verified',
  },
  {
    id: 'dqn',
    demo: 'replay',
    slug: 'dqn',
    type: 'architecture',
    title: t(
      'DQN learns from pixels and reward',
      'DQN lernt aus Pixeln und Belohnung',
      'DQN aprende de píxeles y recompensas',
    ),
    shortDescription: t(
      'Deep Q-Networks combined learned visual representations with action-value learning. Atari games offered a shared test bed for an algorithm trained from image observations and game scores.',
      'Deep Q-Networks kombinierten gelernte visuelle Darstellungen mit Handlungswertlernen. Atari-Spiele boten ein gemeinsames Testfeld für einen Algorithmus, der aus Bildbeobachtungen und Spielständen lernte.',
      'Deep Q-Networks combinaron representaciones visuales aprendidas y valores de acciones. Los juegos Atari proporcionaron pruebas comunes para un algoritmo entrenado con imágenes y puntuaciones.',
    ),
    description: t(
      'A 2013 DeepMind preprint introduced an Atari agent combining convolutional networks and Q-learning. The expanded 2015 Nature study evaluated 49 games using a shared algorithm and architecture. Networks were trained separately for each game. Experience replay and a target network helped stabilize learning. The achievement concerned a defined benchmark, with varying performance across games, rather than a single system mastering every task or a demonstration of general intelligence.',
      'Ein DeepMind-Preprint von 2013 stellte einen Atari-Agenten mit Faltungsnetzen und Q-Lernen vor. Die erweiterte Nature-Studie von 2015 untersuchte 49 Spiele mit gemeinsamem Algorithmus und Architektur. Für jedes Spiel wurde ein eigenes Netz trainiert. Erfahrungswiederholung und ein Zielnetz stabilisierten das Lernen. Die Leistung betraf einen definierten Benchmark mit unterschiedlichen Ergebnissen je Spiel, kein einzelnes System für jede Aufgabe und keinen Nachweis allgemeiner Intelligenz.',
      'Un preprint de DeepMind de 2013 presentó un agente Atari que combinaba redes convolucionales y Q-learning. El estudio ampliado de Nature de 2015 evaluó 49 juegos con un mismo algoritmo y arquitectura. Se entrenaron redes separadas para cada juego. La repetición de experiencias y una red objetivo estabilizaron el aprendizaje. El logro corresponde a un referente concreto, con rendimiento variable, no a un sistema único que dominara todas las tareas ni a una demostración de inteligencia general.',
    ),
    technical: t(
      'Replay samples past transitions; the target network changes more slowly. Together they reduce instability in bootstrapped value learning.',
      'Replay nutzt frühere Übergänge; das Zielnetz verändert sich langsamer. Beides vermindert Instabilität beim Wertlernen mit Bootstrapping.',
      'La repetición muestrea transiciones pasadas; la red objetivo cambia más lentamente. Ambas reducen inestabilidad al aprender valores con bootstrapping.',
    ),
    startDate: '2015',
    domain: 'learning',
    locations: [place('London, United Kingdom', 'Google DeepMind', 51.51, -0.12, 2015)],
    people: ['Volodymyr Mnih', 'Koray Kavukcuoglu', 'David Silver', 'Demis Hassabis'],
    references: ['dqn-2013', 'dqn-2015', 'watkins-dayan-1992'],
    tags: ['reinforcement-learning', 'deep-learning', 'atari'],
    status: 'verified',
  },
  {
    id: 'alphago',
    demo: 'tree-search',
    slug: 'alphago',
    type: 'technology',
    title: t(
      'AlphaGo joins learning and search',
      'AlphaGo verbindet Lernen und Suche',
      'AlphaGo une aprendizaje y búsqueda',
    ),
    shortDescription: t(
      'Networks and tree search worked together to play Go. AlphaGo combined learned evaluations, move selection and planning, showing how different computational approaches could reinforce one another.',
      'Netze und Baumsuche spielten gemeinsam Go. AlphaGo verband gelernte Bewertungen, Zugauswahl und Planung und zeigte, wie unterschiedliche Rechenverfahren einander verstärken können.',
      'Redes y búsqueda en árboles colaboraron para jugar al go. AlphaGo combinó evaluaciones aprendidas, selección de movimientos y planificación, mostrando cómo distintos enfoques podían reforzarse mutuamente.',
    ),
    description: t(
      'The 2016 AlphaGo paper described policy networks for proposing moves, value networks for assessing positions and tree search for planning. Training used human games as well as self-play. The resulting system defeated the European champion Fan Hui in the reported match. AlphaGo Zero in 2017 later learned without human game examples. Keeping these versions distinct makes the changing role of data, search and reinforcement learning visible.',
      'Der AlphaGo-Artikel von 2016 beschrieb Strategienetze für Zugvorschläge, Wertnetze für Stellungsbewertungen und Baumsuche zur Planung. Das Training nutzte menschliche Partien und Selbstspiel. Das System besiegte Europameister Fan Hui im berichteten Wettkampf. AlphaGo Zero lernte 2017 später ohne menschliche Beispielpartien. Die Unterscheidung dieser Versionen macht die wechselnde Rolle von Daten, Suche und verstärkendem Lernen sichtbar.',
      'El artículo de AlphaGo de 2016 describió redes de política para proponer jugadas, redes de valor para evaluar posiciones y búsqueda en árboles para planificar. El entrenamiento utilizó partidas humanas y autojuego. El sistema derrotó al campeón europeo Fan Hui en el encuentro documentado. AlphaGo Zero aprendió después, en 2017, sin ejemplos de partidas humanas. Distinguir las versiones permite entender el papel cambiante de datos, búsqueda y refuerzo.',
    ),
    technical: t(
      'Search evaluates possible continuations using learned guidance. AlphaGo is not simply DQN applied unchanged to a board game.',
      'Suche bewertet mögliche Fortsetzungen mit gelernter Führung. AlphaGo ist keine unveränderte Anwendung von DQN auf ein Brettspiel.',
      'La búsqueda evalúa continuaciones con orientación aprendida. AlphaGo no es una aplicación sin cambios de DQN a un juego de tablero.',
    ),
    startDate: '2016',
    endDate: '2017',
    domain: 'learning',
    locations: [place('London, United Kingdom', 'Google DeepMind', 51.51, -0.12, 2016)],
    people: ['David Silver', 'Aja Huang', 'Demis Hassabis'],
    references: ['alphago-2016', 'alphago-zero-2017'],
    tags: ['reinforcement-learning', 'planning', 'search'],
    status: 'verified',
  },
  {
    id: 'predictive-coding',
    demo: 'prediction',
    slug: 'predictive-coding',
    type: 'concept',
    title: t(
      'Predictive coding in visual cortex',
      'Prädiktive Kodierung im visuellen Kortex',
      'Codificación predictiva en la corteza visual',
    ),
    shortDescription: t(
      'A visual model used downward predictions and upward residual errors. Predictive coding asks whether some cortical responses can be understood through the difference between expected and observed input.',
      'Ein Sehmodell nutzte absteigende Vorhersagen und aufsteigende Restfehler. Prädiktive Kodierung fragt, ob manche kortikalen Antworten die Differenz zwischen erwartetem und beobachtetem Input ausdrücken.',
      'Un modelo visual utilizó predicciones descendentes y errores ascendentes. La codificación predictiva pregunta si algunas respuestas corticales reflejan la diferencia entre entradas esperadas y observadas.',
    ),
    description: t(
      'Rao and Ballard’s 1999 model explained selected visual receptive-field effects using a hierarchy that predicts activity at lower levels. Feedback carries predictions; feedforward activity carries residual errors. Learning from natural images produced features resembling simple-cell receptive fields. This is a proposed computational interpretation of experiments. Its resemblance to prediction tasks in modern machine learning is useful for comparison, but does not establish direct historical influence or biological equivalence.',
      'Rao und Ballard erklärten 1999 ausgewählte rezeptive Feldeffekte mit einer Hierarchie, die Aktivität tieferer Ebenen vorhersagt. Rückkopplung trägt Vorhersagen; aufsteigende Aktivität trägt Restfehler. Lernen aus natürlichen Bildern erzeugte Merkmale, die rezeptiven Feldern einfacher Zellen ähnelten. Dies ist eine vorgeschlagene rechnerische Interpretation von Experimenten. Ähnlichkeiten mit heutigen Vorhersageaufgaben erlauben Vergleiche, belegen aber weder direkten historischen Einfluss noch biologische Gleichwertigkeit.',
      'El modelo de Rao y Ballard de 1999 explicó ciertos efectos de campos receptivos mediante una jerarquía que predice actividad inferior. La retroalimentación transporta predicciones; la actividad ascendente transmite errores residuales. Aprender con imágenes naturales produjo características semejantes a campos receptivos de células simples. Es una interpretación computacional propuesta. Su parecido con tareas predictivas actuales permite comparaciones, pero no demuestra influencia histórica directa ni equivalencia biológica.',
    ),
    technical: t(
      'Prediction errors drive inference about hidden causes. The direction of signals is a model assumption to test experimentally.',
      'Vorhersagefehler steuern die Schätzung verborgener Ursachen. Die Signalrichtung ist eine experimentell zu prüfende Modellannahme.',
      'Los errores guían inferencias sobre causas ocultas. La dirección de las señales es una hipótesis del modelo que debe comprobarse.',
    ),
    startDate: '1999',
    domain: 'neuroai',
    locations: [],
    people: ['Rajesh P. N. Rao', 'Dana H. Ballard'],
    references: ['rao-ballard-1999', 'hubel-wiesel-1962', 'neuroai-2023'],
    tags: ['prediction', 'feedback', 'vision'],
    status: 'verified',
    editorialNotes: t(
      'This node dates a specific model, not the origin of every predictive-coding idea. No single laboratory location is asserted.',
      'Dieser Knoten datiert ein bestimmtes Modell, nicht den Ursprung sämtlicher Ideen prädiktiver Kodierung. Er weist keinen einzelnen Laborstandort zu.',
      'Este nodo fecha un modelo concreto, no el origen de toda codificación predictiva. No se asigna un único laboratorio.',
    ),
  },
  {
    id: 'transformers',
    demo: 'attention',
    slug: 'transformers',
    type: 'architecture',
    title: t(
      'Transformers and learned attention',
      'Transformer und gelernte Aufmerksamkeit',
      'Transformers y atención aprendida',
    ),
    shortDescription: t(
      'Attention-based sequence models changed how representations could combine information across positions. The Transformer began with translation experiments; its mathematical attention mechanism is not a theory of human attention.',
      'Aufmerksamkeit in Sequenzmodellen veränderte die Zusammenführung von Informationen über Positionen hinweg. Der Transformer begann mit Übersetzungsversuchen; seine mathematische Aufmerksamkeit ist keine Theorie menschlicher Aufmerksamkeit.',
      'Los modelos de secuencias basados en atención cambiaron cómo combinar información entre posiciones. El Transformer comenzó con traducción; su mecanismo matemático no constituye una teoría de la atención humana.',
    ),
    description: t(
      'Vaswani and colleagues introduced the Transformer in 2017. Its original encoder-decoder architecture used attention and position information for sequence translation without recurrent or convolutional sequence layers. Later models reused and adapted these building blocks. The shared word attention invites a comparison with psychology, but the operation here computes weighted combinations of representations. Similar terminology does not by itself supply a biological mechanism or a documented lineage from neuroscience.',
      'Vaswani und Kollegen stellten den Transformer 2017 vor. Seine ursprüngliche Encoder-Decoder-Architektur nutzte Aufmerksamkeit und Positionsinformation zur Sequenzübersetzung ohne rekurrente oder Faltungs-Sequenzschichten. Spätere Modelle übernahmen und veränderten diese Bausteine. Der Begriff Aufmerksamkeit lädt zum Vergleich mit Psychologie ein, doch hier werden gewichtete Kombinationen von Darstellungen berechnet. Gemeinsame Begriffe liefern weder einen biologischen Mechanismus noch eine belegte Entwicklungslinie aus der Neurowissenschaft.',
      'Vaswani y sus colaboradores presentaron el Transformer en 2017. Su arquitectura original de codificador y decodificador utilizó atención e información posicional para traducir secuencias sin capas secuenciales recurrentes o convolucionales. Modelos posteriores reutilizaron y adaptaron sus componentes. La palabra atención invita a compararlo con psicología, pero aquí se calculan combinaciones ponderadas de representaciones. Compartir vocabulario no establece un mecanismo biológico ni una genealogía documentada desde la neurociencia.',
    ),
    technical: t(
      'Scaled dot-product attention computes softmax(QKᵀ/√dₖ)V. Queries, keys and values are learned representations, not anatomical structures.',
      'Skalierte Skalarprodukt-Aufmerksamkeit berechnet softmax(QKᵀ/√dₖ)V. Queries, Keys und Values sind gelernte Darstellungen, keine anatomischen Strukturen.',
      'La atención por producto escalar calcula softmax(QKᵀ/√dₖ)V. Consultas, claves y valores son representaciones aprendidas, no estructuras anatómicas.',
    ),
    startDate: '2017',
    domain: 'computing',
    locations: [],
    people: [
      'Ashish Vaswani',
      'Noam Shazeer',
      'Niki Parmar',
      'Jakob Uszkoreit',
      'Llion Jones',
      'Aidan N. Gomez',
      'Łukasz Kaiser',
      'Illia Polosukhin',
    ],
    references: ['transformer-2017', 'bert-2018', 'foundation-2021'],
    tags: ['attention', 'representation', 'language'],
    status: 'verified',
    editorialNotes: t(
      'Google affiliations are documented. The publication is not assigned to one office without more specific location evidence.',
      'Google-Zugehörigkeiten sind belegt. Ohne genauere Ortsbelege wird die Publikation keinem einzelnen Büro zugewiesen.',
      'Las afiliaciones a Google están documentadas. Sin pruebas más precisas, no se atribuye el artículo a una sola oficina.',
    ),
  },
  {
    id: 'self-supervised-learning',
    demo: 'masking',
    slug: 'self-supervised-learning',
    type: 'concept',
    title: t(
      'BERT: learning from withheld words',
      'BERT: Lernen aus verdeckten Wörtern',
      'BERT: aprender con palabras ocultas',
    ),
    shortDescription: t(
      'Training targets can come from the data itself. BERT used masked text to learn representations before adaptation to specific tasks, illustrating a broader history of self-supervised learning.',
      'Trainingsziele können aus den Daten selbst stammen. BERT lernte aus maskiertem Text Darstellungen für spätere Aufgaben und veranschaulicht damit die längere Geschichte selbstüberwachten Lernens.',
      'Los objetivos de entrenamiento pueden proceder de los propios datos. BERT aprendió representaciones con texto enmascarado antes de adaptarse a tareas concretas, ilustrando una historia más amplia del aprendizaje autosupervisado.',
    ),
    description: t(
      'The 2018 BERT preprint described pretraining bidirectional Transformer representations from unlabeled text. Predicting selected masked tokens lets surrounding context supply the learning task. The resulting model can then be adapted using task-specific supervision. This milestone exemplifies self-supervision; it did not invent learning without manually assigned labels. Comparison with sensory prediction is conceptually interesting, while shared prediction objectives alone do not demonstrate the same learning mechanism in brains.',
      'Der BERT-Preprint von 2018 beschrieb das Vortraining bidirektionaler Transformer-Darstellungen aus unbeschriftetem Text. Ausgewählte maskierte Tokens vorherzusagen macht den umgebenden Kontext zur Lernaufgabe. Anschließend lässt sich das Modell mit aufgabenspezifischer Überwachung anpassen. Dieser Meilenstein veranschaulicht Selbstüberwachung; er erfand Lernen ohne manuell vergebene Labels nicht. Vergleiche mit sensorischer Vorhersage sind interessant, doch gemeinsame Vorhersageziele belegen keinen gleichen Lernmechanismus im Gehirn.',
      'El preprint de BERT de 2018 describió el preentrenamiento de representaciones Transformer bidireccionales con texto sin etiquetar. Predecir tokens enmascarados convierte el contexto en una tarea de aprendizaje. Después se adapta el modelo con supervisión específica. Este hito ejemplifica la autosupervisión; no inventó aprender sin etiquetas manuales. La comparación con predicción sensorial es interesante, pero compartir objetivos predictivos no demuestra el mismo mecanismo de aprendizaje cerebral.',
    ),
    technical: t(
      'Pretraining and downstream fine-tuning use different objectives. Self-supervised data still reflect choices about collection, filtering and the prediction task.',
      'Vortraining und anschließende Anpassung nutzen verschiedene Ziele. Selbstüberwachte Daten spiegeln weiterhin Entscheidungen über Sammlung, Filterung und Vorhersageaufgabe wider.',
      'Preentrenamiento y ajuste posterior usan objetivos distintos. Los datos autosupervisados también reflejan decisiones de recopilación, filtrado y tarea predictiva.',
    ),
    startDate: '2018',
    domain: 'learning',
    locations: [],
    people: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
    references: ['bert-2018', 'foundation-2021', 'rao-ballard-1999'],
    tags: ['self-supervision', 'prediction', 'representation'],
    status: 'verified',
    editorialNotes: t(
      'The date marks the BERT preprint, not the origin of self-supervised learning. The conference paper appeared in 2019.',
      'Das Datum bezeichnet den BERT-Preprint, nicht den Ursprung selbstüberwachten Lernens. Der Konferenzartikel erschien 2019.',
      'La fecha corresponde al preprint de BERT, no al origen de la autosupervisión. El artículo de conferencia apareció en 2019.',
    ),
  },
  {
    id: 'alphafold',
    demo: 'geometry',
    slug: 'alphafold',
    type: 'technology',
    title: t(
      'AlphaFold predicts protein structure',
      'AlphaFold sagt Proteinstrukturen vorher',
      'AlphaFold predice estructuras de proteínas',
    ),
    shortDescription: t(
      'Learned models became powerful instruments for biology. AlphaFold2 combined sequence information, structural constraints and specialized architecture to predict protein structures, illustrating a major scientific use of deep learning.',
      'Gelernte Modelle wurden leistungsfähige Werkzeuge der Biologie. AlphaFold2 kombinierte Sequenzinformation, strukturelle Randbedingungen und eine spezialisierte Architektur zur Vorhersage von Proteinstrukturen.',
      'Los modelos aprendidos se convirtieron en instrumentos para la biología. AlphaFold2 combinó secuencias, restricciones estructurales y arquitectura especializada para predecir estructuras de proteínas.',
    ),
    description: t(
      'Following CASP14 in 2020, the 2021 AlphaFold paper reported highly accurate protein structure predictions from Jumper and colleagues. Its architecture incorporated evolutionary and geometric information. Predicted structures are valuable scientific hypotheses, with confidence estimates and limitations; they do not automatically explain molecular dynamics or function. Hassabis and Jumper jointly received half of the 2024 Chemistry Nobel for structure prediction. Baker received the other half for computational protein design.',
      'Nach CASP14 im Jahr 2020 berichtete der AlphaFold-Artikel von Jumper und Kollegen 2021 über hochgenaue Proteinstrukturvorhersagen. Die Architektur berücksichtigte evolutionäre und geometrische Informationen. Vorhergesagte Strukturen sind wertvolle wissenschaftliche Hypothesen mit Konfidenzschätzungen und Grenzen; sie erklären molekulare Dynamik oder Funktion nicht automatisch. Hassabis und Jumper erhielten gemeinsam die Hälfte des Chemienobelpreises 2024 für Strukturvorhersage. Baker erhielt die andere Hälfte für rechnerischen Proteinentwurf.',
      'Tras CASP14 en 2020, el artículo de AlphaFold de Jumper y colaboradores de 2021 presentó predicciones muy precisas de estructuras proteicas. La arquitectura incorporó información evolutiva y geométrica. Las estructuras predichas son hipótesis científicas útiles, con estimaciones de confianza y limitaciones; no explican automáticamente dinámica o función. Hassabis y Jumper recibieron conjuntamente la mitad del Nobel de Química de 2024 por predicción estructural. Baker recibió la otra mitad por diseño computacional de proteínas.',
    ),
    technical: t(
      'Structure prediction estimates a three-dimensional arrangement. It is distinct from predicting every folding pathway or experimental condition.',
      'Strukturvorhersage schätzt eine dreidimensionale Anordnung. Sie sagt nicht sämtliche Faltungswege oder Versuchsbedingungen voraus.',
      'La predicción estructural estima una disposición tridimensional. No predice todas las rutas de plegamiento ni condiciones experimentales.',
    ),
    startDate: '2021',
    domain: 'computing',
    locations: [place('London, United Kingdom', 'DeepMind', 51.51, -0.12, 2021)],
    people: ['John Jumper', 'Richard Evans', 'Demis Hassabis'],
    references: ['alphafold-2021', 'nobel-chemistry-2024'],
    tags: ['protein-structure', 'science', 'deep-learning'],
    status: 'verified',
    nobel: {
      year: 2024,
      reference: 'nobel-chemistry-2024',
      label: t(
        'Chemistry 2024: Hassabis and Jumper shared half for protein structure prediction; Baker received half for protein design',
        'Chemie 2024: Hassabis und Jumper teilten die Hälfte für Proteinstrukturvorhersage; Baker erhielt die Hälfte für Proteinentwurf',
        'Química 2024: Hassabis y Jumper compartieron la mitad por predicción estructural; Baker recibió la mitad por diseño de proteínas',
      ),
    },
  },
  {
    id: 'foundation-models',
    demo: 'transfer',
    slug: 'foundation-models',
    type: 'concept',
    title: t(
      'Foundation models: pretraining and adaptation',
      'Basismodelle: Vortraining und Anpassung',
      'Modelos fundacionales: preentrenamiento y adaptación',
    ),
    shortDescription: t(
      'A model trained on broad data can become a starting point for many tasks. The foundation-model framing highlights both reuse and the way limitations can propagate into downstream applications.',
      'Ein auf breiten Daten trainiertes Modell kann Ausgangspunkt vieler Aufgaben werden. Der Begriff Basismodell betont Wiederverwendung und die Weitergabe von Grenzen an nachgelagerte Anwendungen.',
      'Un modelo entrenado con datos amplios puede servir de punto de partida para muchas tareas. El concepto destaca la reutilización y cómo las limitaciones se transmiten a aplicaciones posteriores.',
    ),
    description: t(
      'The 2021 Stanford report by Bommasani and colleagues introduced foundation models as a framework for understanding broadly trained, adaptable models. It surveyed technical opportunities alongside social and evaluation questions. BERT provides an earlier concrete example of reusable pretrained representations. The term did not invent transfer learning and does not guarantee general intelligence. It directs attention to shared infrastructure: many applications may inherit capabilities, biases and failure modes from one underlying model.',
      'Der Stanford-Bericht von Bommasani und Kollegen führte 2021 Basismodelle als Rahmen für breit trainierte, anpassbare Modelle ein. Er untersuchte technische Möglichkeiten sowie gesellschaftliche und Bewertungsfragen. BERT ist ein früheres konkretes Beispiel wiederverwendbarer vortrainierter Darstellungen. Der Begriff erfand Transferlernen nicht und garantiert keine allgemeine Intelligenz. Er lenkt den Blick auf gemeinsame Infrastruktur: Viele Anwendungen können Fähigkeiten, Verzerrungen und Fehlermuster desselben zugrunde liegenden Modells übernehmen.',
      'El informe de Stanford de Bommasani y colaboradores de 2021 introdujo los modelos fundacionales como marco para modelos entrenados ampliamente y adaptables. Examinó oportunidades técnicas junto a cuestiones sociales y de evaluación. BERT es un ejemplo anterior de representaciones preentrenadas reutilizables. El término no inventó la transferencia ni garantiza inteligencia general. Destaca una infraestructura compartida: muchas aplicaciones pueden heredar capacidades, sesgos y fallos de un mismo modelo.',
    ),
    technical: t(
      'Pretraining supplies shared parameters or representations; adaptation specializes their use. Broad training does not remove the need for task-specific evaluation.',
      'Vortraining liefert gemeinsame Parameter oder Darstellungen; Anpassung spezialisiert ihre Nutzung. Breites Training ersetzt keine aufgabenspezifische Bewertung.',
      'El preentrenamiento aporta parámetros o representaciones compartidos; la adaptación especializa su uso. El entrenamiento amplio no sustituye la evaluación específica.',
    ),
    startDate: '2021',
    domain: 'computing',
    locations: [
      place(
        'Stanford, United States',
        'Stanford University, Center for Research on Foundation Models',
        37.43,
        -122.17,
        2021,
      ),
    ],
    people: ['Rishi Bommasani', 'Drew A. Hudson', 'Percy Liang'],
    references: ['foundation-2021', 'bert-2018'],
    tags: ['pretraining', 'transfer', 'representation'],
    status: 'verified',
  },
  {
    id: 'neuroai',
    demo: 'representations',
    slug: 'neuroai',
    type: 'field',
    title: t(
      'NeuroAI: an open exchange',
      'NeuroAI: ein offener Austausch',
      'NeuroAI: un intercambio abierto',
    ),
    shortDescription: t(
      'Neuroscience can suggest computational principles; artificial models can help test hypotheses about brains. NeuroAI makes this reciprocal exchange explicit while asking which similarities are explanatory and which are superficial.',
      'Neurowissenschaft kann Rechenprinzipien anregen; künstliche Modelle können Gehirnhypothesen prüfen helfen. NeuroAI macht diesen Austausch ausdrücklich und fragt, welche Ähnlichkeiten erklären und welche oberflächlich bleiben.',
      'La neurociencia puede sugerir principios computacionales; los modelos artificiales pueden probar hipótesis cerebrales. NeuroAI explicita este intercambio y pregunta qué semejanzas explican y cuáles son superficiales.',
    ),
    description: t(
      'The 2023 perspective by Zador and colleagues argued for renewed collaboration between neuroscience and machine learning. It is one modern statement of an exchange visible throughout this atlas, not the field’s exact birth. Useful models should make testable predictions, not merely resemble biological vocabulary. Open questions include continual learning, energy efficiency, recurrence and embodiment. Progress may reveal shared principles, but the relationship between artificial performance and biological explanation remains an active research question.',
      'Die Perspektive von Zador und Kollegen von 2023 plädierte für erneuerte Zusammenarbeit zwischen Neurowissenschaft und maschinellem Lernen. Sie formuliert einen Austausch, der im gesamten Atlas sichtbar ist, und markiert keinen exakten Feldursprung. Nützliche Modelle sollten prüfbare Vorhersagen liefern und nicht nur biologisches Vokabular übernehmen. Offene Fragen betreffen kontinuierliches Lernen, Energieeffizienz, Rekurrenz und Verkörperung. Gemeinsame Prinzipien sind möglich; das Verhältnis künstlicher Leistung zu biologischer Erklärung bleibt jedoch Forschungsgegenstand.',
      'La perspectiva de Zador y colaboradores de 2023 defendió una colaboración renovada entre neurociencia y aprendizaje automático. Es una formulación moderna de un intercambio presente en todo el atlas, no el nacimiento exacto del campo. Los modelos útiles deben generar predicciones comprobables, no solo adoptar vocabulario biológico. Quedan abiertas cuestiones de aprendizaje continuo, eficiencia energética, recurrencia y corporeidad. Pueden emerger principios compartidos, pero la relación entre rendimiento artificial y explicación biológica sigue investigándose.',
    ),
    technical: t(
      'A model can predict neural measurements without sharing the brain’s mechanism. Compare competing models and test where their predictions diverge.',
      'Ein Modell kann neuronale Messungen vorhersagen, ohne den Gehirnmechanismus zu teilen. Konkurrierende Modelle müssen anhand unterschiedlicher Vorhersagen geprüft werden.',
      'Un modelo puede predecir medidas neuronales sin compartir el mecanismo cerebral. Hay que comparar modelos y comprobar dónde divergen sus predicciones.',
    ),
    startDate: '2023',
    domain: 'neuroai',
    locations: [],
    people: ['Anthony Zador', 'Sean Escola', 'Blake Richards', 'Bence Ölveczky'],
    references: ['neuroai-2023', 'schultz-dayan-montague-1997', 'rao-ballard-1999'],
    tags: ['open-questions', 'embodiment', 'neural-models'],
    status: 'verified',
    editorialNotes: t(
      'The date marks a perspective article. NeuroAI is an international research community, not one institution or a settled theory.',
      'Das Datum bezeichnet einen Perspektivartikel. NeuroAI ist eine internationale Forschungsgemeinschaft, keine einzelne Institution oder abgeschlossene Theorie.',
      'La fecha señala un artículo de perspectiva. NeuroAI es una comunidad internacional, no una institución única ni una teoría cerrada.',
    ),
  },
  {
    id: 'hodgkin-huxley',
    demo: 'membrane',
    slug: 'hodgkin-huxley',
    type: 'publication',
    title: t(
      'Hodgkin and Huxley model the impulse',
      'Hodgkin und Huxley modellieren den Impuls',
      'Hodgkin y Huxley modelan el impulso',
    ),
    shortDescription: t(
      'Electrical recordings became a quantitative account of nerve signaling. Hodgkin and Huxley modeled how membrane currents generate an action potential, providing a different abstraction from a logical artificial unit.',
      'Elektrische Messungen wurden zu einer quantitativen Erklärung der Nervenleitung. Hodgkin und Huxley modellierten die Entstehung von Aktionspotenzialen durch Membranströme, mit einer anderen Abstraktion als logische künstliche Einheiten.',
      'Los registros eléctricos se convirtieron en una explicación cuantitativa de la señal nerviosa. Hodgkin y Huxley modelaron cómo las corrientes generan potenciales de acción, usando una abstracción distinta de una unidad lógica artificial.',
    ),
    description: t(
      'The 1952 paper combined results from squid giant-axon experiments into equations for membrane currents and excitation. Voltage-dependent sodium and potassium conductances helped explain the shape and propagation of electrical impulses. This biophysical model asks how a biological cell signals. McCulloch and Pitts instead asked what an idealized network could compute. Placing both in the atlas shows why different scientific questions require different levels of description.',
      'Der Artikel von 1952 fasste Ergebnisse am Riesenaxon des Tintenfischs in Gleichungen für Membranströme und Erregung zusammen. Spannungsabhängige Natrium- und Kaliumleitfähigkeiten erklärten Form und Ausbreitung elektrischer Impulse. Dieses biophysikalische Modell fragt, wie eine biologische Zelle Signale erzeugt. McCulloch und Pitts fragten dagegen, was ein idealisiertes Netz berechnen kann. Beide Ansätze zeigen im Atlas, warum verschiedene wissenschaftliche Fragen unterschiedliche Beschreibungsebenen erfordern.',
      'El artículo de 1952 reunió experimentos con el axón gigante de calamar en ecuaciones de corrientes y excitación. Las conductancias de sodio y potasio dependientes del voltaje explicaron la forma y propagación de impulsos eléctricos. Este modelo biofísico pregunta cómo señaliza una célula biológica. McCulloch y Pitts preguntaban qué podía calcular una red idealizada. Juntos muestran por qué distintas preguntas científicas requieren niveles de descripción diferentes.',
    ),
    technical: t(
      'Membrane voltage changes as capacitive and ionic currents balance. Gating variables summarize time-dependent conductance rather than modeling every molecular detail.',
      'Die Membranspannung folgt dem Gleichgewicht kapazitiver und ionischer Ströme. Torvariablen fassen zeitabhängige Leitfähigkeit zusammen, ohne jedes Moleküldetail abzubilden.',
      'El voltaje depende del equilibrio entre corrientes capacitivas e iónicas. Las variables de compuerta resumen conductancias temporales sin representar cada detalle molecular.',
    ),
    startDate: '1952',
    domain: 'neuroscience',
    locations: [
      place(
        'Cambridge, United Kingdom',
        'Physiological Laboratory, University of Cambridge',
        52.2,
        0.12,
        1952,
      ),
    ],
    people: ['Alan L. Hodgkin', 'Andrew F. Huxley'],
    references: ['hodgkin-huxley-1952', 'mcculloch-pitts-1943'],
    tags: ['action-potential', 'electrophysiology', 'biophysics'],
    status: 'verified',
    editorialNotes: t(
      'The map marks the affiliation printed on the 1952 paper, not the location of every experiment in the research program.',
      'Die Karte zeigt die Institution des Artikels von 1952, nicht den Ort jedes Experiments des Forschungsprogramms.',
      'El mapa muestra la afiliación del artículo de 1952, no el lugar de cada experimento del programa.',
    ),
  },
];
