import type { HistoricalEntity, LocalizedText } from '@/types/history';

const t = (en: string, de: string, es: string): LocalizedText => ({ en, de, es });
const award1906 = {
  year: 1906,
  reference: 'nobel-1906',
  label: t(
    'Nobel Prize in Physiology or Medicine, jointly with Golgi and Cajal',
    'Nobelpreis für Physiologie oder Medizin, gemeinsam für Golgi und Cajal',
    'Premio Nobel de Fisiología o Medicina, compartido por Golgi y Cajal',
  ),
};

export const initialEntities: HistoricalEntity[] = [
  {
    id: 'golgi',
    demo: 'staining',
    slug: 'golgi',
    type: 'technology',
    title: t('Golgi’s black reaction', 'Golgis schwarze Reaktion', 'La reacción negra de Golgi'),
    shortDescription: t(
      'A stain made individual nerve cells visible against a crowded background. A new method of seeing opened a dispute about how the nervous system is built.',
      'Eine Färbung machte einzelne Nervenzellen vor einem dichten Hintergrund sichtbar. Eine neue Beobachtungsmethode eröffnete die Debatte über den Aufbau des Nervensystems.',
      'Una tinción permitió distinguir células nerviosas individuales en un tejido denso. Una nueva forma de observar abrió el debate sobre la organización del sistema nervioso.',
    ),
    description: t(
      'In 1873 Camillo Golgi described a staining method developed in Abbiategrasso. Its sparse, dark staining revealed the branching shape of selected nerve cells. Ramón y Cajal later used the method to support a different interpretation of nervous tissue. Golgi defended a continuous network, while Cajal argued for distinct cells. Their shared 1906 Nobel Prize recognized work on nervous-system structure, despite this disagreement.',
      '1873 beschrieb Camillo Golgi eine in Abbiategrasso entwickelte Färbemethode. Die dunkle Färbung weniger ausgewählter Nervenzellen machte deren verzweigte Gestalt erkennbar. Ramón y Cajal nutzte die Methode später, um eine andere Deutung des Nervengewebes zu begründen. Golgi verteidigte ein kontinuierliches Netz, während Cajal für getrennte Zellen argumentierte. Ihr gemeinsamer Nobelpreis von 1906 würdigte die Erforschung der Struktur des Nervensystems trotz dieses Widerspruchs.',
      'En 1873 Camillo Golgi describió una tinción desarrollada en Abbiategrasso. Al teñir oscuramente unas pocas células nerviosas, revelaba sus ramificaciones. Ramón y Cajal empleó después el método para defender una interpretación distinta del tejido nervioso. Golgi sostenía la existencia de una red continua; Cajal defendía células separadas. El Nobel que compartieron en 1906 reconoció sus estudios de la estructura del sistema nervioso pese a esta discrepancia.',
    ),
    technical: t(
      'Selective silver-based staining allows a cell body and its processes to be traced. It reveals morphology, but does not directly measure electrical activity or prove how signals cross between cells.',
      'Eine selektive Silberfärbung lässt Zellkörper und Fortsätze verfolgen. Sie zeigt die Morphologie, misst aber keine elektrische Aktivität und beweist nicht, wie Signale zwischen Zellen übertragen werden.',
      'La tinción selectiva con sales de plata permite seguir el cuerpo celular y sus prolongaciones. Muestra su morfología, pero no mide la actividad eléctrica ni demuestra cómo se transmiten señales entre células.',
    ),
    startDate: '1873',
    domain: 'neuroscience',
    locations: [
      {
        name: 'Abbiategrasso, Italy',
        institution: 'Pio Luogo degli Incurabili',
        lat: 45.4,
        lon: 8.92,
        year: 1873,
      },
    ],
    people: ['Camillo Golgi'],
    references: ['golgi-pavia', 'golgi-black-reaction', 'nobel-1906', 'cajal-lecture'],
    tags: ['microscopy', 'cellular-neuroscience', 'vision-lineage'],
    status: 'verified',
    nobel: award1906,
  },
  {
    id: 'cajal',
    demo: 'arbor',
    slug: 'cajal',
    type: 'person',
    title: t(
      'Ramón y Cajal sees individual cells',
      'Ramón y Cajal erkennt einzelne Zellen',
      'Ramón y Cajal distingue células individuales',
    ),
    shortDescription: t(
      'Careful observations and drawings supported the view that nervous tissue consists of distinct cells. Cajal used Golgi’s technique to reach a competing explanation.',
      'Sorgfältige Beobachtungen und Zeichnungen stützten die Auffassung, dass Nervengewebe aus einzelnen Zellen besteht. Cajal gelangte mit Golgis Technik zu einer konkurrierenden Erklärung.',
      'Observaciones y dibujos cuidadosos apoyaron la idea de que el tejido nervioso está formado por células distintas. Cajal utilizó la técnica de Golgi para defender otra explicación.',
    ),
    description: t(
      'Cajal’s productive Barcelona period began in 1887; 1888 is used here as a milestone in his anatomical work, not his birth date. Studying stained nervous tissue, he argued that cells retain their individuality and communicate through contacts. His 1906 Nobel lecture assembled evidence across preparations and species. Cajal was a central contributor to the neuron doctrine, a collective development rather than a discovery made by one person alone.',
      'Cajals produktive Zeit in Barcelona begann 1887. Hier bezeichnet 1888 einen Meilenstein seiner anatomischen Forschung, nicht sein Geburtsjahr. An gefärbtem Nervengewebe argumentierte er, dass Zellen eigenständig bleiben und über Kontakte kommunizieren. Sein Nobelvortrag von 1906 führte Befunde aus verschiedenen Präparaten und Arten zusammen. Cajal trug wesentlich zur Neuronenlehre bei, die aus gemeinsamer Forschung entstand und keine Entdeckung einer einzigen Person war.',
      'La etapa de Cajal en Barcelona comenzó en 1887. Aquí, 1888 señala un hito de su investigación anatómica, no su nacimiento. Al estudiar tejido teñido, defendió que las células conservan su individualidad y se comunican por contactos. Su conferencia Nobel de 1906 reunió observaciones de diferentes preparaciones y especies. Cajal fue una figura central de la doctrina neuronal, fruto de múltiples contribuciones y no de una sola persona.',
    ),
    technical: t(
      'Drawings are interpretations of microscopic preparations, not photographs of living circuits. Anatomical evidence constrained possible connections; physiological experiments were still needed to explain signaling.',
      'Zeichnungen sind Interpretationen mikroskopischer Präparate, keine Fotografien lebender Schaltkreise. Anatomische Befunde schränkten mögliche Verbindungen ein; zur Erklärung der Signalübertragung waren physiologische Experimente nötig.',
      'Los dibujos interpretan preparaciones microscópicas; no son fotografías de circuitos vivos. La anatomía delimitó las conexiones posibles, mientras que la transmisión de señales exigía experimentos fisiológicos.',
    ),
    startDate: '1888',
    domain: 'neuroscience',
    locations: [
      {
        name: 'Barcelona, Spain',
        institution: 'Universitat de Barcelona',
        lat: 41.39,
        lon: 2.17,
        year: 1888,
      },
    ],
    people: ['Santiago Ramón y Cajal'],
    references: ['cajal-lecture', 'cajal-barcelona', 'nobel-1906', 'nobel-cells'],
    tags: ['microscopy', 'cellular-neuroscience', 'neuron-doctrine'],
    status: 'verified',
    nobel: award1906,
  },
  {
    id: 'neuron-doctrine',
    demo: 'synapse',
    slug: 'neuron-doctrine',
    type: 'concept',
    title: t('The neuron doctrine', 'Die Neuronenlehre', 'La doctrina neuronal'),
    shortDescription: t(
      'The nervous system can be studied as interacting, distinct cells. This anatomical claim is historical context for later computational models, not a complete theory of intelligence.',
      'Das Nervensystem lässt sich als Zusammenspiel eigenständiger Zellen untersuchen. Diese anatomische Aussage bildet den historischen Kontext späterer Rechenmodelle, aber keine vollständige Theorie der Intelligenz.',
      'El sistema nervioso puede estudiarse como un conjunto de células distintas que interactúan. Esta propuesta anatómica aporta contexto a modelos computacionales posteriores, sin constituir una teoría completa de la inteligencia.',
    ),
    description: t(
      'The neuron doctrine brought together evidence that nervous tissue is organized into discrete cells. Waldeyer’s 1891 synthesis and terminology helped consolidate work by Cajal and other anatomists. The date marks that synthesis, not a single decisive experiment. Treating cells as distinct components made questions about their connections explicit. It did not establish that a biological neuron behaves like a binary switch or that an artificial unit reproduces its mechanisms.',
      'Die Neuronenlehre bündelte Befunde, nach denen Nervengewebe aus eigenständigen Zellen besteht. Waldeyers Synthese und Begriffswahl von 1891 fassten Arbeiten Cajals und anderer Anatomen zusammen. Das Datum steht für diese Synthese, nicht für ein einzelnes entscheidendes Experiment. Getrennte Zellen als Bausteine zu betrachten, machte ihre Verbindungen zu einer ausdrücklichen Forschungsfrage. Daraus folgt weder, dass biologische Neuronen binäre Schalter sind, noch dass künstliche Einheiten ihre Mechanismen nachbilden.',
      'La doctrina neuronal reunió pruebas de que el tejido nervioso se organiza en células separadas. La síntesis y terminología de Waldeyer en 1891 consolidaron trabajos de Cajal y otros anatomistas. La fecha corresponde a esa síntesis, no a un único experimento decisivo. Considerar células distintas hizo explícita la pregunta por sus conexiones. No demuestra que una neurona biológica sea un interruptor binario ni que una unidad artificial reproduzca sus mecanismos.',
    ),
    technical: t(
      'A neuron is a biological cell; an artificial unit is a mathematical component. The graph’s link to McCulloch and Pitts expresses historical context, not a documented direct causal chain.',
      'Ein Neuron ist eine biologische Zelle; eine künstliche Einheit ist ein mathematischer Baustein. Die Verbindung zu McCulloch und Pitts bezeichnet historischen Kontext, keine belegte direkte Wirkungskette.',
      'Una neurona es una célula biológica; una unidad artificial es un componente matemático. La conexión con McCulloch y Pitts expresa contexto histórico, no una cadena causal directa documentada.',
    ),
    startDate: '1891',
    domain: 'neuroscience',
    locations: [],
    people: ['Santiago Ramón y Cajal', 'Heinrich Wilhelm Waldeyer', 'Wilhelm His', 'Auguste Forel'],
    references: ['neuron-history', 'cajal-lecture', 'nobel-cells'],
    tags: ['cellular-neuroscience', 'computation-lineage'],
    status: 'verified',
  },
  {
    id: 'mcculloch-pitts',
    demo: 'logic',
    slug: 'mcculloch-pitts',
    type: 'publication',
    title: t(
      'A logical calculus of nervous activity',
      'Ein logischer Kalkül der Nervenaktivität',
      'Un cálculo lógico de la actividad nerviosa',
    ),
    shortDescription: t(
      'McCulloch and Pitts connected idealized nervous activity with propositional logic. Their 1943 model showed what networks of simple artificial units could compute.',
      'McCulloch und Pitts verknüpften idealisierte Nervenaktivität mit Aussagenlogik. Ihr Modell von 1943 zeigte, was Netze einfacher künstlicher Einheiten berechnen können.',
      'McCulloch y Pitts relacionaron actividad nerviosa idealizada y lógica proposicional. Su modelo de 1943 mostró qué podían calcular redes de unidades artificiales simples.',
    ),
    description: t(
      'Warren McCulloch and Walter Pitts proposed a mathematical account of networks using all-or-none activity. Logical operations could be expressed through connected idealized units. The importance lies in the abstraction: selected assumptions about nervous activity became an explicit formal system. The paper does not supply a learning rule or a detailed cellular simulation. Its model belongs to a history of mathematical reasoning about brains, rather than evidence that brains literally operate as digital logic circuits.',
      'Warren McCulloch und Walter Pitts beschrieben Netze mathematisch mithilfe von Alles-oder-nichts-Aktivität. Verbundene idealisierte Einheiten konnten logische Operationen ausdrücken. Entscheidend war die Abstraktion: Ausgewählte Annahmen über Nervenaktivität wurden zu einem expliziten formalen System. Der Artikel liefert weder eine Lernregel noch eine detaillierte Zellsimulation. Das Modell gehört zur mathematischen Erforschung des Gehirns und beweist nicht, dass Gehirne wie digitale Logikschaltungen arbeiten.',
      'Warren McCulloch y Walter Pitts propusieron una descripción matemática de redes con actividad de todo o nada. Unidades idealizadas conectadas podían expresar operaciones lógicas. Su importancia está en la abstracción: ciertas suposiciones sobre actividad nerviosa se convirtieron en un sistema formal. El artículo no ofrece una regla de aprendizaje ni una simulación celular detallada. Pertenece a la investigación matemática del cerebro, sin demostrar que este funcione literalmente como un circuito digital.',
    ),
    technical: t(
      'Units have binary states, fixed thresholds and idealized timing. Excitatory and inhibitory connections determine logical behavior. These assumptions deliberately omit much of a living neuron’s biophysics.',
      'Die Einheiten besitzen binäre Zustände, feste Schwellen und idealisierte Zeitabläufe. Erregende und hemmende Verbindungen bestimmen das logische Verhalten. Diese Annahmen lassen große Teile der Biophysik lebender Neuronen bewusst weg.',
      'Las unidades tienen estados binarios, umbrales fijos y tiempos idealizados. Conexiones excitadoras e inhibidoras determinan su comportamiento lógico. Estas suposiciones omiten gran parte de la biofísica de una neurona viva.',
    ),
    startDate: '1943',
    domain: 'mathematics',
    locations: [
      {
        name: 'Chicago, United States',
        institution: 'Illinois Neuropsychiatric Institute; University of Chicago',
        lat: 41.88,
        lon: -87.63,
        year: 1943,
      },
    ],
    people: ['Warren S. McCulloch', 'Walter Pitts'],
    references: ['mcculloch-pitts-1943'],
    tags: ['logic', 'artificial-units', 'computation-lineage'],
    status: 'verified',
  },
  {
    id: 'perceptron',
    slug: 'perceptron',
    type: 'algorithm',
    title: t(
      'The perceptron learns from examples',
      'Das Perzeptron lernt aus Beispielen',
      'El perceptrón aprende con ejemplos',
    ),
    shortDescription: t(
      'Frank Rosenblatt investigated trainable pattern-recognition systems. Adjusting connection weights offered a route from fixed logical networks to classification learned from examples.',
      'Frank Rosenblatt untersuchte trainierbare Systeme zur Mustererkennung. Veränderbare Verbindungsgewichte eröffneten einen Weg von festen logischen Netzen zur Klassifikation anhand von Beispielen.',
      'Frank Rosenblatt investigó sistemas entrenables de reconocimiento de patrones. Ajustar los pesos de las conexiones abrió un camino desde redes lógicas fijas hasta clasificaciones aprendidas con ejemplos.',
    ),
    description: t(
      'Rosenblatt’s 1958 paper presented the perceptron as a probabilistic approach to information storage and organization. His work at the Cornell Aeronautical Laboratory in Buffalo connected questions about perception with trainable machines. The demonstration here uses a modern two-input linear classifier, not a reconstruction of every feature of his historical system. A straight decision boundary makes learning visible and also exposes a limit: one such unit cannot separate the alternating labels in XOR.',
      'Rosenblatts Artikel von 1958 stellte das Perzeptron als probabilistischen Ansatz zur Speicherung und Organisation von Information vor. Am Cornell Aeronautical Laboratory in Buffalo verband er Fragen der Wahrnehmung mit trainierbaren Maschinen. Die Demonstration verwendet einen modernen linearen Klassifikator mit zwei Eingaben und rekonstruiert nicht sämtliche Eigenschaften seines historischen Systems. Eine gerade Entscheidungsgrenze macht Lernen und eine Grenze sichtbar: Eine einzelne solche Einheit kann die wechselnden Klassen von XOR nicht trennen.',
      'El artículo de Rosenblatt de 1958 presentó el perceptrón como un enfoque probabilístico del almacenamiento y la organización de información. En el Cornell Aeronautical Laboratory de Buffalo relacionó percepción y máquinas entrenables. Esta demostración utiliza un clasificador lineal moderno de dos entradas, sin reconstruir todos los elementos del sistema histórico. Una frontera recta permite observar el aprendizaje y una limitación: una sola unidad de este tipo no separa las etiquetas alternadas de XOR.',
    ),
    technical: t(
      'For binary labels, predict from the sign of w·x + b. On a mistake, update weights toward the correct label. Convergence requires linearly separable training data; it is not guaranteed for arbitrary examples.',
      'Bei binären Klassen entscheidet das Vorzeichen von w·x + b. Bei einem Fehler werden Gewichte in Richtung der richtigen Klasse angepasst. Konvergenz erfordert linear trennbare Trainingsdaten und ist für beliebige Beispiele nicht garantiert.',
      'Para etiquetas binarias, la predicción depende del signo de w·x + b. Si hay un error, los pesos se ajustan hacia la etiqueta correcta. La convergencia requiere datos linealmente separables y no está garantizada para ejemplos arbitrarios.',
    ),
    startDate: '1958',
    domain: 'learning',
    demo: 'perceptron',
    locations: [
      {
        name: 'Buffalo, United States',
        institution: 'Cornell Aeronautical Laboratory',
        lat: 42.89,
        lon: -78.88,
        year: 1958,
      },
    ],
    people: ['Frank Rosenblatt'],
    references: ['rosenblatt-1958', 'rosenblatt-cornell', 'perceptron-course'],
    tags: ['supervised-learning', 'linear-classification', 'computation-lineage'],
    status: 'verified',
  },
  {
    id: 'hubel-wiesel',
    slug: 'hubel-wiesel',
    type: 'experiment',
    title: t(
      'Receptive fields in visual cortex',
      'Rezeptive Felder im visuellen Kortex',
      'Campos receptivos en la corteza visual',
    ),
    shortDescription: t(
      'Hubel and Wiesel recorded how cortical neurons respond to visual patterns. Orientation-selective responses and simple and complex receptive fields suggested ways to organize visual processing.',
      'Hubel und Wiesel zeichneten auf, wie kortikale Neuronen auf visuelle Muster reagieren. Orientierungsselektive Antworten sowie einfache und komplexe rezeptive Felder eröffneten Modelle der visuellen Verarbeitung.',
      'Hubel y Wiesel registraron respuestas de neuronas corticales a patrones visuales. La selectividad a la orientación y los campos receptivos simples y complejos sugirieron formas de organizar el procesamiento visual.',
    ),
    description: t(
      'The 1962 paper studied neurons in the cat’s visual cortex and their responses to patterned stimulation of the eyes. Hubel and Wiesel characterized receptive fields and proposed hierarchical explanations of response properties. Fukushima later explicitly drew on this work. Biological experiments and engineering models should nevertheless remain distinct: a convolutional filter is an idealized operation, not a complete cortical circuit. Hubel and Wiesel shared half of the 1981 Nobel Prize; Roger Sperry received the other half.',
      'Die Studie von 1962 untersuchte Neuronen im visuellen Kortex der Katze und ihre Antworten auf gemusterte Reize. Hubel und Wiesel beschrieben rezeptive Felder und schlugen hierarchische Erklärungen ihrer Eigenschaften vor. Fukushima bezog sich später ausdrücklich darauf. Biologische Experimente und technische Modelle bleiben jedoch verschieden: Ein Faltungsfilter ist eine idealisierte Operation, kein vollständiger kortikaler Schaltkreis. Hubel und Wiesel teilten sich eine Hälfte des Nobelpreises von 1981; die andere erhielt Roger Sperry.',
      'El estudio de 1962 examinó neuronas de la corteza visual del gato y sus respuestas a estímulos visuales. Hubel y Wiesel caracterizaron campos receptivos y propusieron explicaciones jerárquicas. Fukushima se apoyó después explícitamente en este trabajo. Deben distinguirse los experimentos biológicos de los modelos de ingeniería: un filtro convolucional es una operación idealizada, no un circuito cortical completo. Hubel y Wiesel compartieron la mitad del Nobel de 1981; Roger Sperry recibió la otra mitad.',
    ),
    technical: t(
      'A receptive field describes which visual stimuli affect a neuron’s response. Simple and complex cells differ in spatial response structure. Our filter demonstration illustrates selectivity without simulating recorded cells.',
      'Ein rezeptives Feld beschreibt, welche visuellen Reize die Antwort eines Neurons beeinflussen. Einfache und komplexe Zellen unterscheiden sich räumlich in ihren Antworten. Die Filterdemonstration veranschaulicht Selektivität, ohne gemessene Zellen zu simulieren.',
      'Un campo receptivo describe qué estímulos visuales afectan a la respuesta de una neurona. Las células simples y complejas difieren en su organización espacial. La demostración ilustra selectividad sin simular las células registradas.',
    ),
    startDate: '1962',
    domain: 'neuroscience',
    demo: 'orientation',
    locations: [
      {
        name: 'Boston, United States',
        institution: 'Harvard Medical School',
        lat: 42.34,
        lon: -71.1,
        year: 1962,
      },
    ],
    people: ['David H. Hubel', 'Torsten N. Wiesel'],
    references: ['hubel-wiesel-1962', 'hubel-harvard', 'nobel-1981', 'fukushima-1980'],
    tags: ['receptive-fields', 'vision-lineage', 'visual-cortex'],
    status: 'verified',
    nobel: {
      year: 1981,
      reference: 'nobel-1981',
      label: t(
        'Hubel and Wiesel jointly received half of the Physiology or Medicine prize',
        'Hubel und Wiesel erhielten gemeinsam die Hälfte des Medizin-Nobelpreises',
        'Hubel y Wiesel compartieron la mitad del Nobel de Fisiología o Medicina',
      ),
    },
  },
  {
    id: 'neocognitron',
    slug: 'neocognitron',
    type: 'architecture',
    title: t('Fukushima’s Neocognitron', 'Fukushimas Neocognitron', 'El Neocognitrón de Fukushima'),
    shortDescription: t(
      'A layered pattern-recognition model translated ideas about simple and complex cells into an artificial architecture. Its aim was recognition tolerant of changes in position.',
      'Ein mehrschichtiges Modell übersetzte Ideen über einfache und komplexe Zellen in eine künstliche Architektur. Es sollte Muster trotz veränderter Position erkennen.',
      'Un modelo de reconocimiento por capas trasladó ideas sobre células simples y complejas a una arquitectura artificial. Buscaba reconocer patrones pese a cambios de posición.',
    ),
    description: t(
      'Kunihiko Fukushima’s 1980 Neocognitron paper explicitly linked its hierarchical organization to Hubel and Wiesel’s visual-system model. Alternating stages selected features and reduced sensitivity to their exact positions. It is a documented case of biological inspiration becoming an engineering design. Later convolutional networks share important architectural ideas, but differ in training and implementation. In particular, the 1980 model used self-organization without a teacher rather than the supervised backpropagation used in LeNet.',
      'Fukushimas Neocognitron-Artikel von 1980 verknüpfte seinen hierarchischen Aufbau ausdrücklich mit Hubels und Wiesels Modell des visuellen Systems. Abwechselnde Stufen wählten Merkmale aus und verringerten die Empfindlichkeit für deren genaue Position. Hier ist biologische Inspiration für einen technischen Entwurf direkt belegt. Spätere Faltungsnetze teilen wichtige Architekturideen, unterscheiden sich aber in Training und Umsetzung. Das Modell von 1980 nutzte insbesondere Selbstorganisation ohne Lehrer statt des überwachten Backpropagation-Verfahrens von LeNet.',
      'El artículo de Fukushima de 1980 relacionó explícitamente la jerarquía del Neocognitrón con el modelo visual de Hubel y Wiesel. Etapas alternadas seleccionaban rasgos y reducían la sensibilidad a su posición exacta. Es un caso documentado de inspiración biológica aplicada a la ingeniería. Redes convolucionales posteriores comparten ideas arquitectónicas, pero difieren en entrenamiento e implementación. El modelo de 1980 utilizaba autoorganización sin profesor, en lugar de la retropropagación supervisada de LeNet.',
    ),
    technical: t(
      'S-type stages detect features; C-type stages combine local responses to tolerate shifts. Historical “cell” labels name artificial units here. The model’s learning procedure is distinct from gradient-based CNN training.',
      'S-Stufen erkennen Merkmale; C-Stufen kombinieren lokale Antworten und tolerieren Verschiebungen. Die historischen Zellbezeichnungen meinen hier künstliche Einheiten. Das Lernen unterscheidet sich vom gradientenbasierten CNN-Training.',
      'Las etapas S detectan rasgos; las etapas C combinan respuestas locales para tolerar desplazamientos. Aquí, las etiquetas históricas de células designan unidades artificiales. El aprendizaje difiere del entrenamiento de CNN mediante gradientes.',
    ),
    startDate: '1980',
    domain: 'computing',
    demo: 'convolution',
    locations: [
      {
        name: 'Tokyo, Japan',
        institution: 'NHK Broadcasting Science Research Laboratories, Kinuta',
        lat: 35.64,
        lon: 139.61,
        year: 1980,
      },
    ],
    people: ['Kunihiko Fukushima'],
    references: ['fukushima-1980', 'lecun-1998'],
    tags: ['hierarchy', 'vision-lineage', 'biological-inspiration'],
    status: 'verified',
  },
  {
    id: 'backpropagation',
    slug: 'backpropagation',
    type: 'algorithm',
    title: t(
      'Learning internal representations',
      'Interne Repräsentationen lernen',
      'Aprender representaciones internas',
    ),
    shortDescription: t(
      'Backpropagation efficiently calculates how each parameter affects an error. A prominent 1986 paper demonstrated how learning could shape the hidden representations of a multilayer network.',
      'Backpropagation berechnet effizient, wie einzelne Parameter einen Fehler beeinflussen. Eine bekannte Arbeit von 1986 zeigte, wie Lernen interne Repräsentationen eines mehrschichtigen Netzes formen kann.',
      'La retropropagación calcula eficientemente cómo influye cada parámetro en un error. Un destacado artículo de 1986 mostró cómo el aprendizaje podía formar representaciones internas en redes de varias capas.',
    ),
    description: t(
      'Rumelhart, Hinton and Williams showed how error derivatives could guide changes throughout a multilayer network. Hidden units could acquire useful representations through training. The 1986 date marks this influential exposition, not the invention of differentiation or the first appearance of the underlying algorithm. Reverse-mode automatic differentiation has an earlier history, including Linnainmaa’s 1970 work. The method computes a gradient; an optimizer then uses that gradient to update parameters.',
      'Rumelhart, Hinton und Williams zeigten, wie Fehlerableitungen Änderungen im gesamten mehrschichtigen Netz steuern können. Verborgene Einheiten konnten durch Training nützliche Repräsentationen lernen. Das Datum 1986 bezeichnet diese einflussreiche Darstellung, weder die Erfindung der Differentiation noch das erste Auftreten des zugrunde liegenden Algorithmus. Automatische Differentiation im Rückwärtsmodus reicht unter anderem bis zu Linnainmaas Arbeit von 1970 zurück. Das Verfahren berechnet einen Gradienten; ein Optimierer nutzt ihn anschließend zur Parameteranpassung.',
      'Rumelhart, Hinton y Williams mostraron cómo las derivadas del error podían guiar cambios en una red de varias capas. Las unidades ocultas podían aprender representaciones útiles. La fecha de 1986 señala esta influyente exposición, no la invención de la diferenciación ni la primera aparición del algoritmo subyacente. La diferenciación automática inversa tiene antecedentes, incluido el trabajo de Linnainmaa de 1970. El método calcula un gradiente que un optimizador utiliza para actualizar parámetros.',
    ),
    technical: t(
      'The chain rule passes loss derivatives backward through differentiable operations. Gradient descent updates θ ← θ − η∇L. This computational backward pass is not a claim that biological neurons transmit these derivatives.',
      'Die Kettenregel führt Verlustableitungen rückwärts durch differenzierbare Operationen. Gradientenabstieg aktualisiert θ ← θ − η∇L. Dieser rechnerische Rückwärtsdurchlauf behauptet nicht, dass biologische Neuronen solche Ableitungen übertragen.',
      'La regla de la cadena propaga derivadas de la pérdida en sentido inverso. El descenso por gradiente actualiza θ ← θ − η∇L. Este recorrido computacional no implica que las neuronas biológicas transmitan esas derivadas.',
    ),
    startDate: '1986',
    domain: 'learning',
    demo: 'backpropagation',
    locations: [],
    people: ['David E. Rumelhart', 'Geoffrey E. Hinton', 'Ronald J. Williams'],
    references: ['rumelhart-1986', 'autodiff-history'],
    tags: ['optimization', 'representation-learning', 'computation-lineage'],
    status: 'verified',
  },
  {
    id: 'lenet',
    slug: 'lenet',
    type: 'architecture',
    title: t(
      'LeNet: learning to read digits',
      'LeNet lernt Ziffern zu lesen',
      'LeNet aprende a leer dígitos',
    ),
    shortDescription: t(
      'Convolution, shared weights and gradient-based training turned pixel patterns into useful learned features. LeNet-5 made handwritten-digit recognition a concrete application of layered artificial networks.',
      'Faltung, gemeinsame Gewichte und gradientenbasiertes Training verwandelten Pixelmuster in gelernte Merkmale. LeNet-5 machte die Ziffernerkennung zu einer konkreten Anwendung mehrschichtiger künstlicher Netze.',
      'Convolución, pesos compartidos y entrenamiento con gradientes transformaron píxeles en rasgos aprendidos. LeNet-5 convirtió el reconocimiento de dígitos manuscritos en una aplicación concreta de redes artificiales por capas.',
    ),
    description: t(
      'LeCun, Bottou, Bengio and Haffner’s 1998 document-recognition paper described LeNet-5 and a wider framework for trainable recognition systems. The date identifies this reference architecture, not the beginning of convolutional-network research. Local connections and shared weights exploit the structure of images, while gradient-based learning adjusts useful filters. The paper explicitly situates convolutional networks alongside earlier work including the Neocognitron, while distinguishing their supervised learning procedure.',
      'LeCun, Bottou, Bengio und Haffner beschrieben 1998 LeNet-5 sowie ein breiteres Konzept trainierbarer Dokumenterkennung. Das Datum bezeichnet diese Referenzarchitektur, nicht den Beginn der Forschung an Faltungsnetzen. Lokale Verbindungen und gemeinsam verwendete Gewichte nutzen die Struktur von Bildern; gradientenbasiertes Lernen passt Filter an. Der Artikel ordnet Faltungsnetze ausdrücklich in frühere Arbeiten einschließlich des Neocognitrons ein und unterscheidet zugleich ihr überwachtes Lernverfahren.',
      'El artículo de LeCun, Bottou, Bengio y Haffner de 1998 describió LeNet-5 y un marco más amplio de reconocimiento documental entrenable. La fecha identifica esta arquitectura de referencia, no el inicio de las redes convolucionales. Conexiones locales y pesos compartidos aprovechan la estructura de las imágenes, mientras el aprendizaje con gradientes ajusta filtros. El artículo relaciona estas redes con trabajos anteriores, incluido el Neocognitrón, y distingue su procedimiento supervisado de aprendizaje.',
    ),
    technical: t(
      'A filter applies the same parameters across image positions. Subsampling reduces spatial resolution, and later stages combine features for classification. Weight sharing reduces the number of independently learned parameters.',
      'Ein Filter verwendet an verschiedenen Bildpositionen dieselben Parameter. Unterabtastung verringert die räumliche Auflösung, spätere Stufen kombinieren Merkmale zur Klassifikation. Gemeinsame Gewichte reduzieren die Zahl unabhängig gelernter Parameter.',
      'Un filtro aplica los mismos parámetros en distintas posiciones de la imagen. El submuestreo reduce la resolución y etapas posteriores combinan rasgos para clasificar. Compartir pesos reduce los parámetros que deben aprenderse independientemente.',
    ),
    startDate: '1998',
    domain: 'computing',
    demo: 'sharing',
    locations: [
      {
        name: 'Red Bank, United States',
        institution: 'AT&T Labs Research',
        lat: 40.35,
        lon: -74.06,
        year: 1998,
      },
    ],
    people: ['Yann LeCun', 'Léon Bottou', 'Yoshua Bengio', 'Patrick Haffner'],
    references: ['lecun-1998'],
    tags: ['convolution', 'handwriting', 'vision-lineage'],
    status: 'verified',
  },
  {
    id: 'imagenet',
    demo: 'sampling',
    slug: 'imagenet',
    type: 'dataset',
    title: t(
      'ImageNet: data becomes infrastructure',
      'ImageNet: Daten werden Infrastruktur',
      'ImageNet: los datos como infraestructura',
    ),
    shortDescription: t(
      'An organized image collection made large-scale visual recognition measurable. Data gathering, human annotation and benchmark design became central parts of the research story.',
      'Eine strukturierte Bildsammlung machte visuelle Erkennung in großem Maßstab messbar. Datensammlung, menschliche Annotation und Benchmark-Design wurden zentrale Teile der Forschung.',
      'Una colección organizada de imágenes permitió medir el reconocimiento visual a gran escala. Recopilar datos, anotarlos y diseñar evaluaciones pasó a ser parte central de la investigación.',
    ),
    description: t(
      'The 2009 ImageNet paper introduced an image database organized around WordNet categories. Deng and colleagues, including Fei-Fei Li, described collecting candidate images and verifying them with human annotators using Mechanical Turk. The later ImageNet Large Scale Visual Recognition Challenge provided shared tasks and evaluation protocols. ImageNet and the challenge subsets are related but not identical. Their importance demonstrates that progress depends on measurement and research infrastructure as well as algorithms.',
      'Der ImageNet-Artikel von 2009 stellte eine nach WordNet-Kategorien organisierte Bilddatenbank vor. Deng und Kollegen, darunter Fei-Fei Li, beschrieben das Sammeln von Bildern und deren Prüfung durch menschliche Annotatoren über Mechanical Turk. Die spätere ImageNet Large Scale Visual Recognition Challenge stellte gemeinsame Aufgaben und Bewertungsprotokolle bereit. ImageNet und die Wettbewerbsteilmengen hängen zusammen, sind aber nicht identisch. Ihr Stellenwert zeigt, dass Fortschritt neben Algorithmen auch Messverfahren und Forschungsinfrastruktur braucht.',
      'El artículo de ImageNet de 2009 presentó una base de imágenes organizada según categorías de WordNet. Deng y sus colaboradores, incluida Fei-Fei Li, describieron la recopilación de imágenes y su verificación por anotadores mediante Mechanical Turk. El posterior ImageNet Large Scale Visual Recognition Challenge estableció tareas y protocolos comunes. ImageNet y los subconjuntos del concurso están relacionados, pero no son idénticos. Su importancia muestra que el progreso necesita medición e infraestructura, además de algoritmos.',
    ),
    technical: t(
      'A WordNet synset groups synonymous terms. Image labels and train/test partitions define the task being measured. A classification score therefore depends on the dataset and protocol, not only on a model.',
      'Ein WordNet-Synset bündelt synonyme Begriffe. Bildlabels und Trainings-/Testaufteilungen definieren die gemessene Aufgabe. Ein Klassifikationsergebnis hängt daher von Datensatz und Protokoll ab, nicht nur vom Modell.',
      'Un synset de WordNet agrupa términos sinónimos. Las etiquetas y particiones de entrenamiento y prueba definen la tarea evaluada. Una puntuación depende del conjunto de datos y del protocolo, además del modelo.',
    ),
    startDate: '2009',
    domain: 'computing',
    locations: [
      {
        name: 'Princeton, United States',
        institution: 'Princeton University',
        lat: 40.35,
        lon: -74.65,
        year: 2009,
      },
    ],
    people: ['Jia Deng', 'Wei Dong', 'Richard Socher', 'Li-Jia Li', 'Kai Li', 'Fei-Fei Li'],
    references: ['imagenet-2009', 'ilsvrc-2015'],
    tags: ['datasets', 'benchmarks', 'vision-lineage'],
    status: 'verified',
  },
  {
    id: 'alexnet',
    demo: 'rectifier',
    slug: 'alexnet',
    type: 'architecture',
    title: t(
      'AlexNet changes the benchmark',
      'AlexNet verändert den Benchmark',
      'AlexNet transforma el referente',
    ),
    shortDescription: t(
      'A large convolutional network combined GPUs, training data and effective optimization. Its 2012 ImageNet result showed the impact of bringing these ingredients together.',
      'Ein großes Faltungsnetz kombinierte GPUs, Trainingsdaten und wirksame Optimierung. Sein ImageNet-Ergebnis von 2012 zeigte die Wirkung dieses Zusammenspiels.',
      'Una gran red convolucional combinó GPU, datos de entrenamiento y optimización eficaz. Su resultado en ImageNet en 2012 mostró el impacto de reunir estos elementos.',
    ),
    description: t(
      'Krizhevsky, Sutskever and Hinton trained a deep convolutional network at the University of Toronto. Their paper combined rectified linear units, GPU computation, augmentation and dropout. The 2012 competition entry achieved a top-five test error of 15.3%, compared with 26.2% for the runner-up. That entry used multiple networks; the score should not be presented as the result of one isolated model. The advance built on earlier architectures and a substantial dataset and evaluation effort.',
      'Krizhevsky, Sutskever und Hinton trainierten an der Universität Toronto ein tiefes Faltungsnetz. Ihre Arbeit kombinierte gleichgerichtete lineare Einheiten, GPU-Berechnung, Datenaugmentation und Dropout. Der Wettbewerbsbeitrag von 2012 erreichte einen Top-5-Testfehler von 15,3 % gegenüber 26,2 % beim Zweitplatzierten. Dieser Beitrag kombinierte mehrere Netze; die Zahl ist daher kein Ergebnis eines einzelnen isolierten Modells. Der Fortschritt beruhte auf früheren Architekturen sowie umfangreicher Daten- und Evaluationsarbeit.',
      'Krizhevsky, Sutskever y Hinton entrenaron una red convolucional profunda en la Universidad de Toronto. Combinaron unidades lineales rectificadas, cálculo con GPU, aumento de datos y dropout. Su participación de 2012 logró un error de prueba top-5 del 15,3 %, frente al 26,2 % del segundo puesto. Esa participación combinó varias redes; la cifra no corresponde a un único modelo aislado. El avance se apoyó en arquitecturas anteriores y un importante trabajo de datos y evaluación.',
    ),
    technical: t(
      'The core architecture has five convolutional and three fully connected layers. Top-five error counts examples whose correct class is absent from the five highest-scoring predictions. It differs from top-one error.',
      'Die Kernarchitektur besitzt fünf Faltungs- und drei vollständig verbundene Schichten. Der Top-5-Fehler zählt Beispiele, deren richtige Klasse unter den fünf besten Vorhersagen fehlt. Er unterscheidet sich vom Top-1-Fehler.',
      'La arquitectura básica tiene cinco capas convolucionales y tres totalmente conectadas. El error top-5 cuenta los ejemplos cuya clase correcta falta entre las cinco predicciones mejor puntuadas. Difiere del error top-1.',
    ),
    startDate: '2012',
    domain: 'computing',
    locations: [
      {
        name: 'Toronto, Canada',
        institution: 'University of Toronto',
        lat: 43.66,
        lon: -79.4,
        year: 2012,
      },
    ],
    people: ['Alex Krizhevsky', 'Ilya Sutskever', 'Geoffrey E. Hinton'],
    references: ['alexnet-2012', 'ilsvrc-2015'],
    tags: ['deep-learning', 'gpu', 'vision-lineage'],
    status: 'verified',
  },
];
