import type { HistoricalRelationship, LocalizedText } from '@/types/history';

const t = (en: string, de: string, es: string): LocalizedText => ({ en, de, es });
export const expansionRelationships: HistoricalRelationship[] = [
  {
    id: 'doctrine-hebb',
    source: 'neuron-doctrine',
    target: 'hebb',
    type: 'historical-context',
    confidence: 'medium',
    evidence: ['hebb-1949', 'cajal-lecture'],
    description: t(
      'Distinct cells and their connections form the biological setting for Hebb’s proposal; this is contextual, not a claim of direct influence.',
      'Getrennte Zellen und ihre Verbindungen bilden den biologischen Rahmen für Hebbs Vorschlag; dies ist Kontext, kein direkter Einflussnachweis.',
      'Las células separadas y sus conexiones aportan el contexto biológico de Hebb; no se afirma una influencia directa.',
    ),
  },
  {
    id: 'hebb-hopfield',
    source: 'hebb',
    target: 'hopfield',
    type: 'biological-inspiration',
    confidence: 'high',
    evidence: ['hebb-1949', 'hopfield-1982'],
    description: t(
      'Hopfield cites Hebb when discussing connection changes and stored memories, translating a biological learning idea into a simplified network.',
      'Hopfield zitiert Hebb zu Verbindungsänderungen und Erinnerungen und überträgt eine biologische Lernidee auf ein vereinfachtes Netz.',
      'Hopfield cita a Hebb al discutir cambios de conexiones y memoria, trasladando una idea biológica a una red simplificada.',
    ),
  },
  {
    id: 'mcculloch-edvac',
    source: 'mcculloch-pitts',
    target: 'von-neumann',
    type: 'direct-inspiration',
    confidence: 'high',
    evidence: ['edvac-1945', 'mcculloch-pitts-1943'],
    description: t(
      'The EDVAC report explicitly uses McCulloch and Pitts’s neural analogy in discussing logical computing elements.',
      'Der EDVAC-Bericht verwendet ausdrücklich die neuronale Analogie von McCulloch und Pitts zur Beschreibung logischer Rechenelemente.',
      'El informe EDVAC utiliza explícitamente la analogía neuronal de McCulloch y Pitts al describir elementos lógicos de cálculo.',
    ),
  },
  {
    id: 'turing-dartmouth',
    source: 'turing',
    target: 'dartmouth',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['turing-1950', 'dartmouth-proposal', 'dartmouth-recollection'],
    description: t(
      'The Dartmouth proposal discusses Turing machines; McCarthy later identified Turing as an important predecessor to the meeting’s research agenda.',
      'Der Dartmouth-Antrag behandelt Turingmaschinen; McCarthy benannte Turing später als wichtigen Vorläufer des Forschungsprogramms.',
      'La propuesta de Dartmouth discute máquinas de Turing; McCarthy lo identificó después como un precursor importante del programa.',
    ),
  },
  {
    id: 'shannon-dartmouth',
    source: 'shannon',
    target: 'dartmouth',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['dartmouth-proposal', 'shannon-1948'],
    description: t(
      'Shannon coauthored the Dartmouth proposal, providing a documented personal connection between communication theory and the new research project.',
      'Shannon war Mitautor des Dartmouth-Antrags und verbindet damit Kommunikationstheorie personell mit dem neuen Forschungsprojekt.',
      'Shannon fue coautor de la propuesta de Dartmouth, una conexión personal documentada entre teoría de comunicación y el nuevo proyecto.',
    ),
  },
  {
    id: 'cybernetics-dartmouth',
    source: 'cybernetics',
    target: 'dartmouth',
    type: 'historical-context',
    confidence: 'medium',
    evidence: ['wiener-1948', 'dartmouth-proposal'],
    description: t(
      'Cybernetics and Dartmouth addressed overlapping questions about machines and behavior. This contextual edge does not make one the sole origin of the other.',
      'Kybernetik und Dartmouth behandelten überlappende Fragen zu Maschinen und Verhalten. Diese Kontextkante erklärt keine Seite zum alleinigen Ursprung der anderen.',
      'Cibernética y Dartmouth abordaron preguntas relacionadas sobre máquinas y conducta. Esta conexión contextual no presenta una como origen único de la otra.',
    ),
  },
  {
    id: 'edvac-symbolic',
    source: 'von-neumann',
    target: 'symbolic-ai',
    type: 'historical-context',
    confidence: 'medium',
    evidence: ['edvac-1945', 'logic-theory-1956'],
    description: t(
      'Programmable digital computation provided the setting for executable symbolic systems. This is an enabling context, not a sole-inventor lineage.',
      'Programmierbare Digitalrechner bildeten den Rahmen ausführbarer Symbolsysteme. Dies ist ein technischer Kontext, keine Erfinderkette einer Person.',
      'El cálculo digital programable proporcionó el contexto de sistemas simbólicos ejecutables. Es una condición técnica, no una genealogía de inventor único.',
    ),
  },
  {
    id: 'dartmouth-symbolic',
    source: 'dartmouth',
    target: 'symbolic-ai',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['dartmouth-recollection', 'logic-theory-1956'],
    description: t(
      'The summer project and Logic Theorist belong to the same formative research period; the program was not created from scratch by the meeting.',
      'Sommerprojekt und Logic Theorist gehören zur gleichen frühen Forschungsphase; das Programm entstand nicht erst durch die Tagung.',
      'El proyecto de verano y Logic Theorist pertenecen al mismo período formativo; el programa no nació desde cero en la reunión.',
    ),
  },
  {
    id: 'perceptron-critique',
    source: 'perceptron',
    target: 'perceptrons-1969',
    type: 'challenge',
    confidence: 'high',
    evidence: ['minsky-papert-1969', 'rosenblatt-1958'],
    description: t(
      'Minsky and Papert investigated the representational limits of particular perceptron classes, not all possible trainable networks.',
      'Minsky und Papert untersuchten Darstellungsgrenzen bestimmter Perzeptronklassen, nicht sämtlicher trainierbarer Netze.',
      'Minsky y Papert estudiaron los límites de ciertas clases de perceptrones, no de todas las redes entrenables posibles.',
    ),
  },
  {
    id: 'critique-winters',
    source: 'perceptrons-1969',
    target: 'ai-winters',
    type: 'historical-context',
    confidence: 'medium',
    disputed: true,
    evidence: ['minsky-papert-1969', 'haigh-2023', 'agar-2020'],
    description: t(
      'The book is often linked to later setbacks. Its causal importance is disputed; this edge does not claim it caused an entire AI winter.',
      'Das Buch wird oft mit späteren Rückschlägen verbunden. Seine ursächliche Bedeutung ist umstritten; diese Kante behauptet keinen gesamten dadurch verursachten KI-Winter.',
      'El libro se relaciona a menudo con retrocesos posteriores. Su importancia causal se discute; esta arista no afirma que causara todo un invierno.',
    ),
  },
  {
    id: 'winters-hopfield',
    source: 'ai-winters',
    target: 'hopfield',
    type: 'historical-context',
    confidence: 'medium',
    evidence: ['haigh-2023', 'hopfield-1982'],
    description: t(
      'Hopfield’s work illustrates that network research continued within periods sometimes grouped under the winter metaphor.',
      'Hopfields Arbeit zeigt, dass Netzforschung in Zeiträumen weiterging, die teilweise unter die Wintermetapher gefasst werden.',
      'El trabajo de Hopfield ilustra que la investigación en redes continuó durante períodos agrupados a veces bajo la metáfora del invierno.',
    ),
  },
  {
    id: 'hopfield-backprop',
    source: 'hopfield',
    target: 'backpropagation',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['hopfield-1982', 'rumelhart-1986'],
    description: t(
      'These works contributed different approaches to connectionist research: associative retrieval and gradient-based representation learning.',
      'Diese Arbeiten trugen unterschiedliche Ansätze zur konnektionistischen Forschung bei: assoziativen Abruf und gradientenbasiertes Darstellungslernen.',
      'Estos trabajos aportaron enfoques distintos al conexionismo: recuperación asociativa y aprendizaje de representaciones mediante gradientes.',
    ),
  },
  {
    id: 'mnist-lenet',
    source: 'mnist',
    target: 'lenet',
    type: 'dataset-dependency',
    confidence: 'high',
    evidence: ['lecun-1998', 'mnist-creators'],
    description: t(
      'The 1998 paper evaluates LeNet-5 on the modified NIST digit task. This edge denotes evaluation data, not that the dataset invented the architecture.',
      'Der Artikel von 1998 bewertet LeNet-5 auf der modifizierten NIST-Ziffernaufgabe. Die Kante bezeichnet Evaluationsdaten, keinen Ursprung der Architektur.',
      'El artículo de 1998 evalúa LeNet-5 con dígitos NIST modificados. La arista indica datos de evaluación, no que el conjunto inventara la arquitectura.',
    ),
  },
  {
    id: 'mnist-imagenet',
    source: 'mnist',
    target: 'imagenet',
    type: 'conceptual-analogy',
    confidence: 'high',
    evidence: ['mnist-creators', 'imagenet-2009'],
    description: t(
      'Both illustrate how shared datasets support comparison, although their scale, image complexity and label structures differ.',
      'Beide zeigen, wie gemeinsame Datensätze Vergleiche ermöglichen, bei unterschiedlichem Umfang, Bildaufbau und Klassenstruktur.',
      'Ambos muestran cómo los datos compartidos permiten comparaciones, aunque difieren en escala, complejidad visual y estructura de etiquetas.',
    ),
  },
  {
    id: 'bellman-td',
    source: 'bellman',
    target: 'temporal-difference',
    type: 'mathematical-formalization',
    confidence: 'high',
    evidence: ['bellman-1957', 'sutton-1988'],
    description: t(
      'Value recursions connect immediate outcomes and future estimates. Temporal-difference learning turns related recursive structure into updates from experience.',
      'Wertrekursionen verbinden unmittelbare Ergebnisse und künftige Schätzungen. Temporal-Difference-Lernen nutzt verwandte Strukturen für Aktualisierungen aus Erfahrung.',
      'Las recurrencias de valor conectan resultados inmediatos y estimaciones futuras. Las diferencias temporales usan esa estructura para actualizar con experiencia.',
    ),
  },
  {
    id: 'td-q',
    source: 'temporal-difference',
    target: 'q-learning',
    type: 'extension',
    confidence: 'high',
    evidence: ['sutton-1988', 'watkins-dayan-1992'],
    description: t(
      'Q-learning applies temporal-difference updates to action values using a target based on the best estimated next action.',
      'Q-Lernen wendet Temporal-Difference-Aktualisierungen auf Handlungswerte an und verwendet die beste geschätzte Folgehandlung als Ziel.',
      'Q-learning aplica diferencias temporales a valores de acciones con un objetivo basado en la mejor acción siguiente estimada.',
    ),
  },
  {
    id: 'td-dopamine',
    source: 'temporal-difference',
    target: 'dopamine',
    type: 'mathematical-formalization',
    confidence: 'high',
    evidence: ['sutton-1988', 'schultz-dayan-montague-1997'],
    description: t(
      'Temporal-difference error supplied a computational interpretation of particular phasic dopamine responses during reward learning.',
      'Der Temporal-Difference-Fehler lieferte eine rechnerische Interpretation bestimmter phasischer Dopaminantworten beim Belohnungslernen.',
      'El error de diferencias temporales aportó una interpretación computacional de ciertas respuestas fásicas de dopamina al aprender recompensas.',
    ),
  },
  {
    id: 'q-dqn',
    source: 'q-learning',
    target: 'dqn',
    type: 'extension',
    confidence: 'high',
    evidence: ['watkins-dayan-1992', 'dqn-2015'],
    description: t(
      'DQN approximates action values with a deep network and adds stabilizing procedures; tabular convergence guarantees do not transfer automatically.',
      'DQN nähert Handlungswerte mit einem tiefen Netz an und ergänzt Stabilisierungsverfahren; tabellarische Konvergenzgarantien übertragen sich nicht automatisch.',
      'DQN aproxima valores con una red profunda y añade estabilización; las garantías de convergencia tabular no se transfieren automáticamente.',
    ),
  },
  {
    id: 'alexnet-dqn',
    source: 'alexnet',
    target: 'dqn',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['alexnet-2012', 'dqn-2015'],
    description: t(
      'DQN uses convolutional representation learning in an action-value system. This places visual deep learning in a new task setting.',
      'DQN nutzt Faltungsnetze zur Darstellungsbildung in einem Handlungswertsystem und setzt visuelles tiefes Lernen damit für eine andere Aufgabe ein.',
      'DQN utiliza representaciones convolucionales en un sistema de valores de acciones, llevando el aprendizaje visual profundo a otra tarea.',
    ),
  },
  {
    id: 'dqn-alphago',
    source: 'dqn',
    target: 'alphago',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['dqn-2015', 'alphago-2016'],
    description: t(
      'Both belong to DeepMind’s deep reinforcement-learning program. AlphaGo uses a different combination of policy, value and tree-search methods.',
      'Beide gehören zu DeepMinds Programm des tiefen verstärkenden Lernens. AlphaGo kombiniert Strategie-, Wert- und Baumsuchverfahren auf andere Weise.',
      'Ambos pertenecen al programa de refuerzo profundo de DeepMind. AlphaGo combina de otra manera políticas, valores y búsqueda en árboles.',
    ),
  },
  {
    id: 'symbolic-alphago',
    source: 'symbolic-ai',
    target: 'alphago',
    type: 'conceptual-analogy',
    confidence: 'medium',
    evidence: ['logic-theory-1956', 'alphago-2016'],
    description: t(
      'Both use guided search, but over different objects and with different heuristics. This is a comparison, not a claim of direct descent.',
      'Beide nutzen gelenkte Suche über verschiedene Objekte und mit anderen Heuristiken. Dies ist ein Vergleich, keine Behauptung direkter Abstammung.',
      'Ambos usan búsqueda guiada sobre objetos distintos y con otras heurísticas. Es una comparación, no una afirmación de descendencia directa.',
    ),
  },
  {
    id: 'hubel-predictive',
    source: 'hubel-wiesel',
    target: 'predictive-coding',
    type: 'mathematical-formalization',
    confidence: 'high',
    evidence: ['hubel-wiesel-1962', 'rao-ballard-1999'],
    description: t(
      'Receptive-field observations become targets for a later computational explanation involving hierarchical prediction and feedback.',
      'Beobachtete rezeptive Felder werden zum Gegenstand einer späteren rechnerischen Erklärung mit hierarchischer Vorhersage und Rückkopplung.',
      'Las observaciones de campos receptivos se convierten en objetivos de una explicación computacional con predicción jerárquica y retroalimentación.',
    ),
  },
  {
    id: 'backprop-transformers',
    source: 'backpropagation',
    target: 'transformers',
    type: 'implementation',
    confidence: 'high',
    evidence: ['rumelhart-1986', 'transformer-2017'],
    description: t(
      'Transformer parameters are optimized through differentiable computations. Backpropagation supplies gradients; attention specifies the architecture.',
      'Transformer-Parameter werden durch differenzierbare Berechnungen optimiert. Backpropagation liefert Gradienten; Aufmerksamkeit bestimmt die Architektur.',
      'Los parámetros Transformer se optimizan mediante cálculos diferenciables. La retropropagación aporta gradientes; la atención define la arquitectura.',
    ),
  },
  {
    id: 'transformers-bert',
    source: 'transformers',
    target: 'self-supervised-learning',
    type: 'implementation',
    confidence: 'high',
    evidence: ['transformer-2017', 'bert-2018'],
    description: t(
      'BERT uses Transformer encoders for bidirectional text representations and masked-token pretraining.',
      'BERT nutzt Transformer-Encoder für bidirektionale Textdarstellungen und Vortraining mit maskierten Tokens.',
      'BERT utiliza codificadores Transformer para representaciones bidireccionales y preentrenamiento con tokens enmascarados.',
    ),
  },
  {
    id: 'prediction-selfsupervision',
    source: 'predictive-coding',
    target: 'self-supervised-learning',
    type: 'conceptual-analogy',
    confidence: 'medium',
    evidence: ['rao-ballard-1999', 'bert-2018'],
    description: t(
      'Both organize learning around prediction. Their objectives and mechanisms differ, and this edge asserts no direct historical influence.',
      'Beide organisieren Lernen um Vorhersage. Ziele und Mechanismen unterscheiden sich; die Kante behauptet keinen direkten historischen Einfluss.',
      'Ambos organizan aprendizaje alrededor de predicción. Difieren en objetivos y mecanismos; no se afirma influencia histórica directa.',
    ),
  },
  {
    id: 'bert-foundation',
    source: 'self-supervised-learning',
    target: 'foundation-models',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['bert-2018', 'foundation-2021'],
    description: t(
      'The foundation-model report explicitly includes BERT as an example of broad pretraining followed by adaptation.',
      'Der Bericht zu Basismodellen nennt BERT ausdrücklich als Beispiel breiten Vortrainings mit anschließender Anpassung.',
      'El informe sobre modelos fundacionales incluye explícitamente BERT como ejemplo de preentrenamiento amplio y adaptación.',
    ),
  },
  {
    id: 'transformers-alphafold',
    source: 'transformers',
    target: 'alphafold',
    type: 'extension',
    confidence: 'high',
    evidence: ['transformer-2017', 'alphafold-2021'],
    description: t(
      'AlphaFold2 adapts attention-based components to protein information and geometric constraints, rather than reusing a language model unchanged.',
      'AlphaFold2 passt Aufmerksamkeitsbausteine an Proteininformation und geometrische Bedingungen an, statt ein Sprachmodell unverändert zu übernehmen.',
      'AlphaFold2 adapta componentes de atención a información proteica y restricciones geométricas, sin reutilizar sin cambios un modelo lingüístico.',
    ),
  },
  {
    id: 'dopamine-neuroai',
    source: 'dopamine',
    target: 'neuroai',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['schultz-dayan-montague-1997', 'neuroai-2023'],
    description: t(
      'The reward-prediction account is an example of computational learning theory informing biological interpretation, a central direction of NeuroAI.',
      'Die Belohnungsvorhersage zeigt, wie rechnerische Lerntheorie biologische Deutungen prägt, eine zentrale Richtung von NeuroAI.',
      'La predicción de recompensas muestra cómo la teoría computacional informa interpretaciones biológicas, una dirección central de NeuroAI.',
    ),
  },
  {
    id: 'predictive-neuroai',
    source: 'predictive-coding',
    target: 'neuroai',
    type: 'historical-context',
    confidence: 'high',
    evidence: ['rao-ballard-1999', 'neuroai-2023'],
    description: t(
      'Models of cortical prediction illustrate the exchange between biological observations and proposed computational principles.',
      'Modelle kortikaler Vorhersage veranschaulichen den Austausch zwischen biologischen Beobachtungen und vorgeschlagenen Rechenprinzipien.',
      'Los modelos de predicción cortical ilustran el intercambio entre observaciones biológicas y principios computacionales propuestos.',
    ),
  },
  {
    id: 'foundation-neuroai',
    source: 'foundation-models',
    target: 'neuroai',
    type: 'conceptual-analogy',
    confidence: 'medium',
    evidence: ['foundation-2021', 'neuroai-2023'],
    description: t(
      'Broadly trained models raise comparative questions about representation and adaptation. Task performance alone does not establish biological validity.',
      'Breit trainierte Modelle eröffnen Vergleiche zu Darstellung und Anpassung. Aufgabenleistung allein belegt keine biologische Gültigkeit.',
      'Los modelos amplios plantean comparaciones sobre representación y adaptación. El rendimiento no establece por sí solo validez biológica.',
    ),
  },
  {
    id: 'hh-neuroai',
    source: 'hodgkin-huxley',
    target: 'neuroai',
    type: 'historical-context',
    confidence: 'medium',
    evidence: ['hodgkin-huxley-1952', 'neuroai-2023'],
    description: t(
      'Quantitative biological models provide a contrasting level of explanation to artificial-network models. Their scientific questions need not be identical.',
      'Quantitative biologische Modelle bieten eine andere Erklärungsebene als künstliche Netzmodelle. Ihre wissenschaftlichen Fragen müssen nicht identisch sein.',
      'Los modelos biológicos cuantitativos ofrecen otro nivel explicativo que las redes artificiales. Sus preguntas científicas no tienen por qué coincidir.',
    ),
  },
  {
    id: 'mcculloch-hh',
    source: 'mcculloch-pitts',
    target: 'hodgkin-huxley',
    type: 'conceptual-analogy',
    confidence: 'high',
    evidence: ['mcculloch-pitts-1943', 'hodgkin-huxley-1952'],
    description: t(
      'Both use mathematics to study nervous systems, but logical computation and membrane biophysics require different abstractions.',
      'Beide untersuchen Nervensysteme mathematisch, doch logische Berechnung und Membranbiophysik erfordern verschiedene Abstraktionen.',
      'Ambos estudian sistemas nerviosos matemáticamente, pero cálculo lógico y biofísica de membrana requieren abstracciones distintas.',
    ),
  },
];
