import type { HistoricalRelationship, LocalizedText } from '@/types/history';

const t = (en: string, de: string, es: string): LocalizedText => ({ en, de, es });

export const initialRelationships: HistoricalRelationship[] = [
  {
    id: 'golgi-cajal',
    source: 'golgi',
    target: 'cajal',
    type: 'methodological-enabler',
    confidence: 'high',
    description: t(
      'Cajal used Golgi’s staining method to investigate nervous tissue and reach a different anatomical interpretation.',
      'Cajal nutzte Golgis Färbemethode zur Untersuchung von Nervengewebe und gelangte zu einer anderen anatomischen Deutung.',
      'Cajal utilizó la tinción de Golgi para estudiar tejido nervioso y alcanzar una interpretación anatómica distinta.',
    ),
    evidence: ['cajal-lecture', 'golgi-pavia'],
  },
  {
    id: 'cajal-doctrine',
    source: 'cajal',
    target: 'neuron-doctrine',
    type: 'extension',
    confidence: 'high',
    description: t(
      'Cajal’s anatomical observations supplied important evidence for a doctrine developed by several researchers.',
      'Cajals anatomische Beobachtungen lieferten wichtige Belege für eine von mehreren Forschenden entwickelte Lehre.',
      'Las observaciones anatómicas de Cajal aportaron pruebas importantes a una doctrina desarrollada por varios investigadores.',
    ),
    evidence: ['cajal-lecture', 'neuron-history'],
  },
  {
    id: 'golgi-doctrine',
    source: 'golgi',
    target: 'neuron-doctrine',
    type: 'challenge',
    confidence: 'high',
    description: t(
      'Golgi’s reticular interpretation challenged the view of separate cells, even though his technique helped support that view.',
      'Golgis retikuläre Deutung widersprach der Vorstellung getrennter Zellen, obwohl seine Methode diese Vorstellung stützte.',
      'La interpretación reticular de Golgi cuestionaba la separación celular, aunque su técnica ayudó a demostrarla.',
    ),
    evidence: ['cajal-lecture', 'nobel-cells'],
  },
  {
    id: 'doctrine-mcculloch',
    source: 'neuron-doctrine',
    target: 'mcculloch-pitts',
    type: 'historical-context',
    confidence: 'medium',
    description: t(
      'Distinct biological cells provide historical context for models of connected units. This edge does not assert a documented direct influence.',
      'Eigenständige biologische Zellen bilden den historischen Kontext für Modelle verbundener Einheiten. Diese Kante behauptet keinen belegten direkten Einfluss.',
      'Las células biológicas separadas aportan contexto histórico a modelos de unidades conectadas. Esta arista no afirma una influencia directa documentada.',
    ),
    evidence: ['cajal-lecture', 'mcculloch-pitts-1943'],
  },
  {
    id: 'mcculloch-perceptron',
    source: 'mcculloch-pitts',
    target: 'perceptron',
    type: 'historical-context',
    confidence: 'high',
    description: t(
      'Rosenblatt discusses earlier logical network models, including McCulloch and Pitts, while pursuing a probabilistic account of learning.',
      'Rosenblatt diskutiert frühere logische Netzmodelle, darunter McCulloch und Pitts, während er einen probabilistischen Lernansatz verfolgt.',
      'Rosenblatt examina modelos lógicos anteriores, incluidos McCulloch y Pitts, al desarrollar un enfoque probabilístico del aprendizaje.',
    ),
    evidence: ['rosenblatt-1958', 'mcculloch-pitts-1943'],
  },
  {
    id: 'perceptron-backprop',
    source: 'perceptron',
    target: 'backpropagation',
    type: 'historical-context',
    confidence: 'high',
    description: t(
      'Both address learning in artificial networks. Backpropagation trains differentiable hidden layers; it is not the same update rule as the perceptron.',
      'Beide behandeln Lernen in künstlichen Netzen. Backpropagation trainiert differenzierbare verborgene Schichten und verwendet eine andere Regel als das Perzeptron.',
      'Ambos estudian el aprendizaje en redes artificiales. La retropropagación entrena capas ocultas diferenciables y utiliza una regla distinta de la del perceptrón.',
    ),
    evidence: ['rosenblatt-1958', 'rumelhart-1986', 'autodiff-history'],
  },
  {
    id: 'hubel-neocognitron',
    source: 'hubel-wiesel',
    target: 'neocognitron',
    type: 'biological-inspiration',
    confidence: 'high',
    description: t(
      'Fukushima explicitly cites Hubel and Wiesel’s hierarchical model when explaining the Neocognitron’s S-type and C-type stages.',
      'Fukushima bezieht sich bei der Erklärung der S- und C-Stufen ausdrücklich auf Hubels und Wiesels hierarchisches Modell.',
      'Fukushima cita explícitamente el modelo jerárquico de Hubel y Wiesel al explicar las etapas S y C del Neocognitrón.',
    ),
    evidence: ['fukushima-1980', 'hubel-wiesel-1962'],
  },
  {
    id: 'neocognitron-lenet',
    source: 'neocognitron',
    target: 'lenet',
    type: 'extension',
    confidence: 'high',
    description: t(
      'The LeNet paper acknowledges the Neocognitron as an architectural precedent and distinguishes the gradient-based supervised training procedure.',
      'Der LeNet-Artikel nennt das Neocognitron als architektonischen Vorläufer und unterscheidet das gradientenbasierte überwachte Training.',
      'El artículo de LeNet reconoce el Neocognitrón como precedente arquitectónico y distingue el entrenamiento supervisado basado en gradientes.',
    ),
    evidence: ['lecun-1998', 'fukushima-1980'],
  },
  {
    id: 'backprop-lenet',
    source: 'backpropagation',
    target: 'lenet',
    type: 'implementation',
    confidence: 'high',
    description: t(
      'LeNet uses backpropagation to compute gradients for training a convolutional architecture on labelled examples.',
      'LeNet verwendet Backpropagation zur Gradientenberechnung beim Training einer Faltungsarchitektur mit beschrifteten Beispielen.',
      'LeNet utiliza retropropagación para calcular gradientes al entrenar una arquitectura convolucional con ejemplos etiquetados.',
    ),
    evidence: ['lecun-1998'],
  },
  {
    id: 'lenet-imagenet',
    source: 'lenet',
    target: 'imagenet',
    type: 'historical-context',
    confidence: 'medium',
    description: t(
      'A teaching transition from handwritten digits to large-scale image categories. It does not claim that LeNet caused the creation of ImageNet.',
      'Ein didaktischer Übergang von handgeschriebenen Ziffern zu großen Bildkategorien. Er behauptet nicht, LeNet habe die Entstehung von ImageNet verursacht.',
      'Una transición didáctica de dígitos manuscritos a categorías visuales a gran escala. No afirma que LeNet causara la creación de ImageNet.',
    ),
    evidence: ['lecun-1998', 'imagenet-2009'],
  },
  {
    id: 'lenet-alexnet',
    source: 'lenet',
    target: 'alexnet',
    type: 'extension',
    confidence: 'high',
    description: t(
      'AlexNet builds on the convolutional-network family and cites LeCun and colleagues, while changing scale, nonlinearities and computation.',
      'AlexNet baut auf der Familie der Faltungsnetze auf und zitiert LeCun und Kollegen; Maßstab, Nichtlinearitäten und Berechnung ändern sich.',
      'AlexNet desarrolla la familia de redes convolucionales y cita a LeCun y colaboradores, con cambios de escala, no linealidades y cálculo.',
    ),
    evidence: ['alexnet-2012', 'lecun-1998'],
  },
  {
    id: 'imagenet-alexnet',
    source: 'imagenet',
    target: 'alexnet',
    type: 'dataset-dependency',
    confidence: 'high',
    description: t(
      'ImageNet challenge data supplied the training and evaluation setting for the reported 2012 result.',
      'Die ImageNet-Wettbewerbsdaten bildeten die Trainings- und Evaluationsgrundlage des berichteten Ergebnisses von 2012.',
      'Los datos del concurso ImageNet proporcionaron el entorno de entrenamiento y evaluación del resultado de 2012.',
    ),
    evidence: ['alexnet-2012', 'ilsvrc-2015'],
  },
  {
    id: 'backprop-alexnet',
    source: 'backpropagation',
    target: 'alexnet',
    type: 'implementation',
    confidence: 'high',
    description: t(
      'Gradient-based training adjusted the network’s parameters, with GPU computation making the large training workload practical.',
      'Gradientenbasiertes Training passte die Netzparameter an; GPU-Berechnung machte den großen Trainingsaufwand praktikabel.',
      'El entrenamiento basado en gradientes ajustó los parámetros; el cálculo con GPU hizo viable la gran carga de entrenamiento.',
    ),
    evidence: ['alexnet-2012'],
  },
];
